RedHatInsights/vulnerability-engine

docker-compose.devel.yml, docker-compose.yml, evaluator/Dockerfile, evaluator/entrypoint.sh, evaluator/main.py, listener/Dockerfile, listener/entrypoint.sh, listener/main.py, manager/Dockerfile, manager/entrypoint.sh, manager/main.py
Containers for basic services according to architectural proposal.
To be consistent with VMaas project I've changed names of the services to nouns
(instead of verbs from proposal).
=> Stub for vulnerability containers

examples/README.md
=> examples: added README with instructions.

listener/entrypoint.sh, listener/mqueue.py, listener/reposcan_listener.py, listener/upload_listener.py, listener/utils.py
Minimal listener implementation, still in progress.
=> Basic listener [WIP]

database/ve_db_postgresql.sql
This addresses sprint task VMAAS-124 to extend DB schema to support historical data
=> add mitigated vulnerabilities table

conf/database-connection-evaluator.env, evaluator/Dockerfile, evaluator/database/database_handler.py, evaluator/evaluator.py
This is only the first part of changes. In this PR I added DB handler only.
=> evaluator: add DB handler.

evaluator/evaluator.py, evaluator/mock_listener.py
group ID for a Kafka consumer
add logger interface
fix Kafka service name for the mock_listener
=> Evaluator result 2 DB. PART I.

Dockerfile-database, docker-compose.yml, evaluator/evaluator.py
=> Save VMaaS results to the DB.

conf/manager.env, manager/common.py
Additional fix to the PR #47
I missed that there is wrong env variable name.
=> manager: Applications in the Insights Platform are expected to read the  environment variable $PATH_PREFIX.

conf/listener.env, evaluator/evaluator.py, listener/mqueue.py, listener/upload_listener.py
- rules does not provide cve list yet, evaluator is guessing it from rule names
- error keys from evaluated rules are not stored in db yet
=> initial evaluation of rules

manager/common.py, manager/main.py, manager/vulnerabilities_handler.py
Errors should be reported in certain format, provide a method that takes care of it.
=> Manager: provide a general wrapper for error reporting

manager/vulnerabilities_handler.py
as we have some information about cve synced in cve_metadata table, there's no need to ask vmaas for that information
=> don't call vmaas for the information we already have

manager/vulnerabilities_handler.py
with c5b1c0a6f98f5541bec291d469e38fe687846671 we don't need this import anymore
=> remove not needed import

manager/cve_handler.py, manager/error_key_handler.py, manager/vulnerabilities_handler.py
these files are not 755 (they're 644) and aren't meant to be executed directly
=> remove shebangs on not directly executable files

Dockerfile-manager, database/peewee_handler.py, database/peewee_model.py, manager/common.py, manager/cve_handler.py, manager/error_key_handler.py, manager/list_view.py, manager/main.py, manager/vulnerabilities_handler.py, scripts/3scale-mock
- using peewee ORM to easily build queries
- currently only 2 lists APIs in manager:
- /r/insights/platform/vulnerability/v1/vulnerabilities/cves
- /r/insights/platform/vulnerability/v1/vulnerabilities/errorkeys
- only single filtering value supported currently (but can be searched in multiple DB columns)
- example usage:
`./scripts/3scale-mock curl -k "https://vulnerability-engine-manager-vulnerability.192.168.42.14.nip.io/r/insights/platform/vulnerability/v1/vulnerabilities/cves?filter=speculative%20execution%20of%20instructions&sort=-cvss_score,public_date&page_size=2&page=2" | python -m json.tool`
- example output:
```
{
"data": [
{
"attributes": {
"celebrity": true,
"cvss_score": "5.500",
"description": "An industry-wide issue was found in the way many modern microprocessor designs …
```
=> Introduce filtering, sorting and pagination support

database/peewee_model.py, database/ve_db_postgresql.sql, evaluator/evaluator.py, manager/system_handler.py, manager/vulnerabilities_handler.py
This should be what's needed for VMAAS-196 sprint task.
It likely does a good bit of VMAAS-195 as well.
=> update schema to use impact mapping table

manager/vulnerabilities_handler.py
Fixes couple of errors introduced by PR #79
=> Fix errors introduced by #79

Dockerfile-manager, manager/common.py, manager/vulnerabilities_handler.py
+ introduces universal function for argument parsing and conversion
=> implement filtering by cvss and public_date ranges

manager/vulnerabilities_handler.py
performance drop was visible if show_all == true due to join with cve_impact table
performance has been improved from ~2400 ms to ~140 ms
=> improve performance of /vulnerabilities/cves API

manager/cve_handler.py, manager/error_key_handler.py
Fixes #65 /cves API and also few places where we didn't send 404 as JSON
=> Fix #65 - return data in correct format (in regards to JSON API SPEC)

manager/system_handler.py
Implements filtering by publis_date and cvss ranges just like vulnerabilities/cves API
=> fix #96 - teach systems/$ID/cves about filtering by publish_date and cvss ranges

manager/common.py, manager/cve_handler.py, manager/system_handler.py, manager/vulnerabilities_handler.py
using GET parameter - "data_format=csv"
=> support csv data output format

.gitignore, .travis.yml, database/ve_db_dev_data.sql, manager/test/test.py, wait-for-postgres.sh
Introduce testing infrastructure (main goal of this PR) and some simple tests to check that API does not break.
=> introduce tests

Dockerfile-manager, manager/main.py, scripts/new-release.sh
Just a simple helper-script to make a new branch and add a tag.
=> add script to make a release (new branch a tag).

manager/system_handler.py, manager/vulnerabilities_handler.py
sometimes public date can be null which causes issues
=> fix #111 - convert to isoformat only if we have the object to convert

manager/main.py
as we don't know how system ID will look like, loosen requirements a bit
=> loosen requirements for system ID

.travis.yml, Dockerfile-manager, manager/common.py, manager/main.py
Each call to manager-API is now a Counter.
Exported at "curl -X GET http://<VULN-ENGINE-MACHINE>:8300/metrics"
=> Added prometheus support to manager

database/peewee_model.py, database/ve_db_postgresql.sql, evaluator/evaluator.py, manager/error_key_handler.py, manager/vulnerabilities_handler.py
This PR:
* updates schema and code to support rules engine results details
* updates schema and code to link CVEs and rules engine results
* fixes logic issues in when evaluating both vmaas and rules engine results
* attempts to update peewee model and manager code to support new schema and data model
=> Update schema and code to support rules engine results details

database/peewee_model.py, database/ve_db_postgresql.sql, manager/common.py, manager/cve_handler.py, manager/main.py, manager/rule_handler.py, manager/status_handler.py, manager/system_handler.py, manager/vulnerabilities_handler.py
* schema/model changes
* READ access to system_handler and cve_handler
* UPDATE access via status_handler POST
=> Status flag support

Dockerfile-evaluator, Dockerfile-evaluator.rhel7, Dockerfile-listener, Dockerfile-listener.rhel7, Dockerfile-manager, Dockerfile-manager.rhel7, evaluator/entrypoint.sh, evaluator/evaluator.py, listener/entrypoint.sh, listener/listener.py, listener/upload_listener.py, listener/vmaas_listener.py, manager/cve_handler.py, manager/entrypoint.sh, manager/list_view.py, manager/main.py, manager/rule_handler.py, manager/status_handler.py, manager/system_handler.py, manager/vulnerabilities_handler.py, run_tests.sh
Make imports valid in the source code repo, with advantages like:
- no problem running unit tests
- no problem running linters and analyzers (flake8, pylint, ...)
- no problem with IDEs and editors features like code completion
Fixes https://github.com/RedHatInsights/vulnerability-engine/issues/174
=> Fix project structure so imports are valid

common/peewee_model.py, database/ve_db_dev_data.sql, database/ve_db_postgresql.sql, listener/archive_parser.py, listener/upload_listener.py, manager/rule_handler.py
this value is not used in manager, is in inventory, it's redundant to parse it from archive in vulnerability
=> delete all occurrences of display_name/hostname

listener/upload_listener.py
missed by #179 and is crashing in CI
=> fixing one more column than expected

listener/archive_parser.py, listener/upload_listener.py, listener/utils.py
- full exception is logged in case of error
- presence of /etc listing in archive is optional (to mark system as satellite-managed)
- repository list is optional, best-effort vulnerability check in vmaas is performed if repo list is not available from RHSM
- package list is mandatory
=> VMAAS-304 - improve archive parsing

manager/status_handler.py
Jiri - changed status_handler to do updates the Right Way for PeeWee. I wasn't able to recreate the apparent-caching issue you were having - can you test w/this PR and let me know what, if any, impact it has on you?
=> Make sure status-update actually updates

listener/archive_parser.py, listener/upload_listener.py, listener/utils.py
if there's module information in the insights archive, extract it and store it into VMaaS JSON so it can be used in evaluation
=> store module information in VMaaS JSON

tests/schemas.py, tests/test_manager.py, tests/vuln_testcase.py
* new manager unit tests
* fixes to schema and response checking
=> New manager unit tests and fixes

requirements.txt
=> kafka is not requirement

evaluator/evaluator.py
- sync CVE metadata from one place
- call VMAAS APIs from one place
- retry VMAAS requests
=> VMAAS-362, VMAAS-316 - fix wrong DB insert

manager/base.py, manager/cve_handler.py, manager/list_view.py, manager/system_handler.py, manager/test/test.py, manager/vulnerabilities_handler.py, tests/schemas.py, tests/test_links.py
Respond to *both* page/page_size/pages and limit/offset/total_items. ListView query now
uses .limit(lim).offset(offset).__iter__ instead of paginate(page, page-size)
=> VMAAS-384 - Move to limit/offset pagination

manager/status_handler.py
migrating status setting into PATCH method as it should be according to IPP, while also leaving functionality in POST so we have time to migrate and delete POST later
=> move status setting into PATCH method

manager/main.py, manager/status_handler.py, tests/manager_tests/test_manager.py
- Status handler output is not compliant with IPP
- Status handler allows setting status for satellite_managed systems and opted_out systems
=> Status handler fixes

.travis.yml, evaluator/evaluator.py
- lock systems before evaluation
- single commit after evaluation is done
- ignore when not able to insert cve_metadata stanza (it was done by someone else and it's fine)
=> evaluator scalability fixes

listener/archive_parser.py
```
$ echo '{"package_list": ["kernel-4.19.13-300.fc29.x86_64", "kernel-4.19.15-300.fc29.x86_64", "kernel-4.20.8-200.fc29.x86_64"], "repository_list": ["fedora-29"]}' | ./scripts/generate_insights_archive.py -o /tmp/insights-archive.tar.gz -
$ ./3scale-mock -a 123456 curl -X POST -F "upload=@/tmp/insights-archive.tar.gz" http://localhost:8100/api/v1/upload
$ docker exec -it vulnerability-engine-database bash -c "psql -U ve_db_admin vulnerability"
vulnerability=> select vmaas_json from system_platform ;
vmaas_json                                          
---------------------------------------------------------------------------------------------------------
{"package_list": ["kernel-0:4.20.8-200.fc29.x86_64"], "repository_list": ["fedora-29"]}
```
=> only evaluate latest version of each package

manager/base.py, manager/cve_handler.py, manager/list_view.py, manager/system_handler.py, manager/test/test.py, manager/vulnerabilities_handler.py, tests/manager_tests/test_links.py, tests/manager_tests/test_manager.py
* link-stanza links should now include all args passed into the API
* More/better tests
The leaking abstractions between Handler and View are really painful - this
part of the architecture neds to be revisted and tightened up.
=> Accepted PR for links-stanza was missing an entire commit. Here it is.

database/README.md
Missed this when I moved some files around in database.
=> update database readme with new location of files

.travis.yml, conf/apidoc.env, manager.spec.yaml, manager/README.md, manager/base.py, manager/cve_handler.py, manager/main.py, manager/status_handler.py, manager/system_handler.py, manager/test/test.py, manager/vulnerabilities_handler.py, requirements-manager.txt, requirements.txt, tests/manager_tests/schemas.py, tests/manager_tests/test_links.py, tests/manager_tests/test_manager.py, tests/manager_tests/vuln_testcase.py
Information about connexion can be found in newly added `manager/README.md` and https://github.com/zalando/connexion
Performance impact:
=> rewrite into connexion(Flask application)

listener/archive_parser.py, listener/upload_listener.py, platform_mock/platform_mock.py
no need to parse it since https://github.com/RedHatInsights/insights-pup/pull/80 was merged
=>  satellite_managed fact is now included in incoming message

.coveragerc, run_tests.sh, tests/listener_tests/test_archive_parser.py, tests/listener_tests/test_upload_listener.py
pylint ignores dirs without `__init__.py`
=> fix pylint on missed files

manager/base.py, tests/conftest.py, tests/evaluator_tests/conftest.py, tests/manager_tests/test_cve_handler.py, tests/manager_tests/test_manager.py, tests/manager_tests/test_status_handler.py
This PR brings up coverage of all `manager/*_handler.py` to 100% and for all other files it leaves just extreme corner cases not covered by unit tests.
=> enhance tests

manager/base.py
connexion is doing check for int value for us, there's no need
to do it one more time in our code
=> simplify _check_int_arg function

manager/base.py, manager/main.py, scripts/3scale-mock, tests/manager_tests/test_manager.py, tests/manager_tests/vuln_testcase.py
Merge after entitlements are provided by 3scale
=> add entitlement checking for API

manager/base.py, scripts/3scale-mock, tests/manager_tests/test_manager.py, tests/manager_tests/vuln_testcase.py
previously 'entitlements' was a key inside 'identity' now it's new key
=> actual entitlements implementation differs from proposal

tests/listener_tests/test_upload_listener.py
=> remove unused arg

Dockerfile.test, README.md, docker-compose.test.yml, run_tests.sh
- enabled tests running using docker-compose
=> Docker test

.coveragerc
https://coverage.readthedocs.io/en/coverage-4.2/excluding.html#advanced-exclusion
=> restore functionality of # pragma: no cover

common/peewee_model.py, manager.spec.yaml, manager/main.py, manager/version_handler.py, tests/manager_tests/conftest.py, tests/manager_tests/test_manager.py, tests/utils.py
```
$ curl http://localhost:8300/api/vulnerability/v1/version
{
"application_version": "latest",
"database_version": 5
}
```
=> improve version API to provide database version

common/mqueue.py, common/webhooks.py, platform_mock/entrypoint.sh, tests/vmaas_sync_tests/conftest.py, tests/vmaas_sync_tests/test_vmaas_sync.py, vmaas_sync/register_webhooks.py, vmaas_sync/vmaas_sync.py
Created new file in `common`, `webhooks.py` which contain logic for registration to webhook service.
Registration script to webhook service can be found in `vmaas_sync/register_webhooks.py` and should be run in pre-deploy hook in OpenShift.
Changes done to `vmaas_sync/vmaas_sync.py` are self-explanatory.
=> Initial webhook integration

manager/status_handler.py, tests/manager_tests/test_status_handler.py
Better error message, and changed response code from 500 to 400.
=> Error 500 with PATCH /status

database/schema/upgrade_scripts/008-improve-cache-refresh-procedures.sql, database/schema/ve_db_postgresql.sql, manager.spec.yaml, manager/base.py, manager/main.py, manager/refresh_handler.py, scripts/3scale-mock, tests/manager_tests/schemas.py, tests/manager_tests/test_readonly.py, tests/manager_tests/test_refresh_handler.py, tests/manager_tests/vuln_testcase.py
- only internal accounts (RH employees) are allowed to call these refresh APIs.
- global "refresh all" function doesn't have callable API intentionally because it's too heavy
=> improve system/cve caching functions and provide interface in manager to call them

manager.spec.yaml
Fix data field displaying
Add missing items to meta part
=> Swagger - response schema

database/schema/upgrade_scripts/011-delete_system_manager.sql, database/schema/ve_db_postgresql.sql, listener/upload_listener.py, manager.spec.yaml, manager/base.py, manager/system_handler.py, tests/manager_tests/schemas.py, tests/manager_tests/test_readonly.py, tests/manager_tests/test_system_handler.py, tests/manager_tests/vuln_testcase.py
see VMAAS-577 for more details
=> support deleting systems using API to fix inconsistent states

Dockerfile-platform-mock, requirements-listener.txt, requirements-manager.txt, requirements.txt
to fix security issuer reported by GitHub
=> Upgraded pyyaml version

LICENSE
=> Added LICENSE file GPLv2

requirements.txt, run_tests.sh
The [idea](https://github.com/RedHatInsights/vulnerability-engine/pull/378#discussion_r303063457)
=> Add requirements check for the CI pipelines.

Dockerfile-apidoc, conf/apidoc.env, docker-compose.yml, manager/main.py, requirements-manager.txt, tests/manager_tests/test_manager.py
available on http://127.0.0.1:8300/api/vulnerability/ui/
no need for extra service
=> use swagger UI provided natively instead of extra container

Jenkinsfile-smoke.groovy
Description - https://github.com/RedHatInsights/e2e-deploy/blob/master/docs/pipeline.md#overview
=> run smoke tests against PR to stable branch

README.md, common/peewee_model.py, database/schema/upgrade_scripts/017-rh-acc-table.sql, database/schema/upgrade_scripts/018-rh-acc-fg-keys.sql, database/schema/upgrade_scripts/019-rh-acc-funs.sql, database/schema/ve_db_dev_data.sql, database/schema/ve_db_postgresql.sql, evaluator/evaluator.py, listener/upload_listener.py, manager/cve_handler.py, manager/refresh_handler.py, manager/status_handler.py, manager/system_handler.py, manager/vulnerabilities_handler.py, tests/data/truncate_dev_data.sql, tests/listener_tests/test_upload_listener.py, vmaas_sync/vmaas_sync.py
- Added `rh_account` table to database.
- Used `rh_account_id` columns instead of `rh_account`.
- Updated touched python code and tests.
=> Rh account table

manager/system_handler.py
=> fixed rh_account_number pairing in SystemCvesView

database/upgrade/upgrade.py
Found this minor typo during review of a PR.
=> Fix typo in log message

Dockerfile-database, Dockerfile-database.rhel7, Dockerfile-evaluator, Dockerfile-evaluator.rhel7, Dockerfile-listener, Dockerfile-listener.rhel7, Dockerfile-manager, Dockerfile-manager.rhel7, Dockerfile-platform-mock, Dockerfile-vmaas-sync, Dockerfile-vmaas-sync.rhel7, requirements-platform-mock.txt, scl-enable.sh, wait-for-services.sh
removed scl-enable.sh usage
used python3 by default
=> Simplified components Dockerfiles

Dockerfile-database, Dockerfile-database.rhel7, Dockerfile-evaluator, Dockerfile-evaluator.rhel7, Dockerfile-listener, Dockerfile-listener.rhel7, Dockerfile-manager, Dockerfile-manager.rhel7, Dockerfile-vmaas-sync, Dockerfile-vmaas-sync.rhel7, manager/version_handler.py, run_tests.sh, scripts/generate_manifest.sh, scripts/new-release.sh
- to satisfy a request from production security team
=> Added deps manifest to dockerfiles

requirements-evaluator.txt, requirements-listener.txt, requirements-vmaas-sync.txt
newer version doesn't seem to work in prod correctly, queue wasn't processing (it seemed as it is processing but offset wasn't commited) and application disconnected kafka connection after a while
after I tried this revert it's working fine
=> revert kafka client version due to problems in production

common/peewee_model.py, common/utils.py, database/schema/upgrade_scripts/021-store-more-cve-metadata.sql, database/schema/ve_db_postgresql.sql, manager.spec.yaml, manager/base.py, manager/cve_handler.py, manager/system_handler.py, manager/vulnerabilities_handler.py, tests/manager_tests/schemas.py, tests/manager_tests/test_cve_handler.py, vmaas_sync/vmaas_sync.py
Also added redhat_url and secondary_url to cve_metadata table and removed vmaas_call in 
/v1​/cves​/{cve_id}
=> Inconsistent empty values in API response

Dockerfile-database, Dockerfile-database.rhel7
=> increase number of max connections

manager/cve_handler.py, manager/status_handler.py
also remove leading and trailing spaces
=> set text to NULL when there's blank string incoming

database/schema/ve_db_postgresql.sql
Other failing tests are expected.
=> remove grant on deleted table

monitoring/grafana/provisioning/dashboards/vulnerability-dashboard.json
=> don't trigger alerts when evaluator.recalc queue exceeds 100

manager/base.py, manager/status_handler.py, manager/system_handler.py, tests/manager_tests/test_system_handler.py
This ISE was caused by ValueError being thrown by postgres driver, added validation
for this specific endpoint, that removes invalid strings.
=> Fix ISE when receiving \u0000 in inventory_id

ocupgrader.yml
config for https://github.com/jdobes/ocupgrader tool
=> add initial ocupgrader config

manager/base.py, manager/system_handler.py
Added utility function for removing NUL characters from string, applied to standard list argument parsers.
=> Fix null filter handling in in filter & sort params

common/failed_cache.py, evaluator/evaluator.py, listener/upload_listener.py, tests/listener_tests/test_upload_listener.py
Add failed cache to remember failed upload or delete messages
=> Mechanism to remember not processed uploads

manager/report_handler.py
set the executive report to include the day on the edge of interval ex: public_date >= (today - X)
=> Discrepancy between executive report and vulnerabilities/cves reporting for last X days

manager/Dockerfile
not available from UBI8 repo, use postgresql repo
=> fix(manager): install psql tool

common/mqueue.py, common/utils.py, conf/listener.env, evaluator/evaluator.py, listener/upload_listener.py, monitoring/grafana/provisioning/dashboards/vulnerability-dashboard.json, platform_mock/entrypoint.sh, platform_mock/platform_mock.py, tests/listener_tests/test_upload_listener.py, tests/vmaas_sync_tests/test_vmaas_sync.py, vmaas_sync/vmaas_sync.py
- to use `platform.inventory.host-egress` instead of legacy `platform.upload.available`
=> refactor code to use platform.inventory.host-egress format

manager.spec.yaml, manager/base.py, manager/report_handler.py, tests/manager_tests/schemas.py, tests/manager_tests/test_report_handler.py
Calculate percenage of cve's score using largest remainder method
=> feat(manager): add percentage of cves  for executive report

common/utils.py, evaluator/evaluator.py
fix(evaluator): track only new uploads
fix(common): use current timestamp in msg
=> Integrate with payload-tracker bugfix

taskomatic/jobs/rules_details.py
Plase do not merge till I fix webhooks for taskomatic.
=> fix(taskomatic): there might be rules without knowledgebase article

Jenkinsfile-smoke.groovy
depends on https://github.com/RedHatInsights/insights-pipeline-lib/pull/71
=> chore: lower resource consumption for smoke tests

.travis.yml, Dockerfile.test, advisor_listener/Dockerfile, evaluator/Dockerfile, listener/Dockerfile, manager/Dockerfile, metrics/Dockerfile, platform_mock/Dockerfile, scripts/openshift-debugger/Dockerfile, taskomatic/Dockerfile, vmaas_sync/Dockerfile
This reverts commit 3b443c7d6777590985a4b4ad3318d60a98a3dada.
=> Revert "chore: Revert "disable pipenv check because pyup.io is down""

.travis.yml, Dockerfile.test, README.md, advisor_listener/Dockerfile, docker-compose.test.yml, docker-compose.yml, evaluator/Dockerfile, listener/Dockerfile, manager/Dockerfile, metrics/Dockerfile, platform_mock/Dockerfile, scripts/devel-compose, scripts/openshift-debugger/Dockerfile, scripts/openshift-debugger/debugger.yml, taskomatic/Dockerfile, vmaas_sync/Dockerfile
same as in vmaas
PIPENV_CHECK=0 docker-compose up --build
=> chore: make PIPENV_CHECK configurable

scripts/import_rules_from_git.py
@jdobes The only unknown for me is how we want to run this script.
=> chore: add a script for importing rules directly from source

manager.spec.yaml, manager/system_handler.py, manager/vulnerabilities_handler.py, tests/manager_tests/test_system_handler.py, tests/manager_tests/test_vulnerabilities_handler.py
previously when cvss_to parameter was used, we returned zero results
=> fix(manager): fix cvss_to filtering parameter

Jenkinsfile-smoke.groovy
it shouldn't be needed anymore and it started to execute rbac tests
=> chore: remove iqe-rbac-plugin

manager.spec.yaml, manager/base.py, manager/report_handler.py, manager/vulnerabilities_handler.py, tests/manager_tests/schemas.py
- /vulnerabilities/cves now returns in meta number of user managed systems
=> feat(manager): add system_count for vuln/cves endpoint

.gitignore, common/peewee_model.py, database/schema/upgrade_scripts/069-add_advisories_list.sql, database/schema/ve_db_dev_data.sql, database/schema/ve_db_postgresql.sql, manager.spec.yaml, manager/cve_handler.py, tests/manager_tests/schemas.py, vmaas_sync/vmaas_sync.py
Also added advisories synchronisation from vmaas and changed /cves endpoint to return advisories list in response
=> Add advisories_list column to database

docker-compose.yml, monitoring/grafana/Dockerfile, monitoring/grafana/dashboards/grafana-dashboard-clouddot-insights-vulnerability-engine.configmap.yml, monitoring/grafana/datasources.yml
=> remove vmaas panels as they were migrated to separate dashboard

conf/taskomatic.env, database/schema/upgrade_scripts/073-taskomatic_cyndi_grant.sql, database/schema/ve_db_postgresql.sql, monitoring/grafana/dashboards/grafana-dashboard-clouddot-insights-vulnerability-engine.configmap.yml, monitoring/prometheus/prometheus.yml, taskomatic/jobs/db_metrics.py, taskomatic/taskomatic.py
Basic few metrics:
- count of systems in system_platform
- count of systems in inventory.hosts
- size (bytes) of individual DB tables
Panels on Grafana dashboard included.
=> provide advanced DB metrics

manager.spec.yaml, manager/cve_handler.py, manager/filters.py, manager/system_handler.py, tests/manager_tests/schemas.py
=> feat(manager): add filter for sap_sids

platform_mock/platform_mock.py
causing schema error on /cves/{CVE}/affected_systems response
=> fix(platform-mock): empty list of should be inserted instead of empty dict

manager.spec.yaml, manager/system_handler.py, tests/manager_tests/schemas.py
is there any other way without repeating my self by adding similar code as  `/systems/` ?
=> VULN-1394 feat: Add opt_out info in systems/ids response

CHANGELOG.md, common/constants.py, common/peewee_model.py, database/schema/upgrade_scripts/075-rules_impact_table.sql, database/schema/ve_db_dev_data.sql, database/schema/ve_db_postgresql.sql, entrypoint.sh, manager.spec.yaml, manager/api_status_handler.py, manager/base.py, manager/cve_handler.py, manager/filters.py, manager/list_view.py, manager/system_handler.py, platform_mock/platform_mock.py, taskomatic/jobs/rules_git_sync.py, tests/manager_tests/schemas.py, tests/manager_tests/test_links.py, tests/manager_tests/test_manager.py, tests/manager_tests/test_system_handler.py
just before partitioning of system_vulnerabilities_active
=> stable 1.74.0 -> 1.76.0

manager.spec.yaml, manager/cve_handler.py, manager/system_handler.py, tests/manager_tests/schemas.py
also, added some missing filters
=> VULN-1411 {inventory_id}/cves/ids should accept advisory filter

manager.spec.yaml, manager/system_handler.py
Also there was a mistake in the API documentation.
=> VULN-1395 fix(manager): leave opted-out systems at bottom of sort for /systems

manager/report_handler.py
Again, this caused inconsistencies.
=> fix(manager): add cyndi join to /report

conf/manager.env, manager/base.py, manager/cve_handler.py, manager/system_handler.py
=> VULN-1517 Consume new API endpoint for errata linking

advisor_listener/advisor_listener.py, common/utils.py
=> VULN-1445: refactor(advisor_listener): split payload tracker for advisor and others

taskomatic/jobs/delete_systems.py
=> VULN-1533 - fix(manager): systems before deadline should be deleted, not on the contrary

manager/base.py, manager/dashboard_handler.py, manager/vulnerabilities_handler.py
=> VULN-1468: cyndi join by using them only when needed

manager.spec.yaml, manager/report_handler.py
=> fix: return rule  name instead of error key

database/schema/upgrade_scripts/082-system_vulnerabilities_cve_index.sql, database/schema/ve_db_postgresql.sql, manager/dashboard_handler.py, manager/report_handler.py, manager/system_handler.py, manager/vulnerabilities_handler.py
=> VULN-1506 - fix(manager): optimize queries

manager/dashboard_handler.py, manager/report_handler.py
=> fix(manager): correctly get sum of CVEs

manager/system_handler.py
=> fix(manager): fixing typo, rule vulnerabilities should be counted

common/utils.py, conf/vmaas-sync.env, tests/vmaas_sync_tests/test_vmaas_sync.py, vmaas_sync/vmaas_sync.py
=> feat(vmaas_sync): use internal ca cert for requesting known exploits

vmaas_sync/vmaas_sync.py
=> fix(vmaas_sync): fix sync exploits bug

advisor_listener/advisor_listener.py
=> fix(advisor_listener): fix missing rules only flag

manager.healthz.spec.yaml, manager/admin.py, manager/main.py, tests/manager_tests/vuln_testcase.py, vmaas_sync/vmaas_sync.py
The health point is "duplicated" in manager to not break status page checking and also to have pretty link for customers.
=> chore: change health check endpoints to healthz

common/peewee_model.py, manager.spec.yaml, manager/cve_handler.py, manager/dashboard_handler.py, manager/filters.py, manager/report_handler.py, manager/system_handler.py, manager/vulnerabilities_handler.py, tests/manager_tests/schemas.py, tests/manager_tests/test_system_handler.py, tests/manager_tests/test_vulnerabilities_handler.py
`/cve/{cve_id}` - add known_exploit bool 
`/vulnerabilities/cves` - add known_exploit bool + filtering 
`/systems/{system_id}/cves` - add known_exploit bool + filtering 
`/report/executive` - add known_exploit bool
`/dashboard` - add exploited_cves_count
=>  VULN-1566 propagate known exploits into API

Dockerfile, manager/admin.py
=> fix: add healthz specs to manager

Pipfile, Pipfile.lock, tests/Pipfile, tests/Pipfile.lock
=> chore: bump up gunicorn version

manager.spec.yaml, manager/filters.py, manager/system_handler.py, manager/vulnerabilities_handler.py, tests/manager_tests/schemas.py
=> VULN-1612 Fix known_exploit filter

database/schema/upgrade_scripts/087-bigserial-migration.sql, database/schema/ve_db_postgresql.sql
=> VULN-1384 feat(database): use bigserial instead of serial

manager/base.py, manager/cve_handler.py, manager/filters.py, manager/list_view.py, manager/system_handler.py, platform_mock/platform_mock.py, tests/manager_tests/test_links.py
=> VULN-1496 Incorrect pagination with filter

advisor_listener/advisor_listener.py, common/status_app.py, evaluator/evaluator.py, listener/upload_listener.py, taskomatic/taskomatic.py
=> VULN-1603 feat: add healthz endpoint for missing components

advisor_listener/advisor_listener.py, common/status_app.py, common/utils.py, evaluator/evaluator.py, listener/upload_listener.py, taskomatic/taskomatic.py, vmaas_sync/vmaas_sync.py
=> chore: change db checks to be asynchronous

manager.spec.yaml
=> VULN-1624 known_exploit query param missing in /ids

manager.spec.yaml
The example values and some descriptions were wrong.
=> chore: refactor query parameter examples

manager/dashboard_handler.py
=> fix(manager): optimize query

Dockerfile, database/Dockerfile, database/Dockerfile.centos, scripts/generate_manifest.sh, scripts/get_app_version.sh
=> VULN-1640 - chore: update to current manifest format

manager/dashboard_handler.py
=> fix(manager): inner join should filter out null/zero rows directly

manager.spec.yaml, manager/base.py, tests/manager_tests/schemas.py
=> feat(manager): add publish date field for rules

common/backoffice_proxy.py, common/utils.py, metrics/metrics_gather.py, vmaas_sync/vmaas_sync.py
=> VULN-1610 start using different mail for metrics

manager/cve_handler.py, manager/list_view.py, manager/system_handler.py, manager/vulnerabilities_handler.py, tests/manager_tests/test_links.py
=> VULN-1569 Secondary sort key for CVEs

vmaas_sync/vmaas_sync.py
=> VULN-1611 Calling vmaas sync API in prod results in 504

listener/upload_listener.py
=> VULN-1655 Implement releasever filtering in listener

common/status_app.py, tests/vmaas_sync_tests/test_vmaas_sync.py, vmaas_sync/vmaas_sync.py
- All helper functions were moved to the BaseView aka. the View for each endpoint.
- Websocket now works on async loop, checks if there is a need to reconnect everytime and waits for msgs in infinite loop
- Methods bounded to the endpoint are implemented in the specific View class
=> refactor(vmaas_sync): switch from tornado to aiohttp

conf/taskomatic.env
=> chore: decrease threshold and run the system deletion job more often

manager.spec.yaml, manager/filters.py, manager/vulnerabilities_handler.py, tests/manager_tests/test_cve_handler.py, tests/manager_tests/test_manager.py, tests/manager_tests/test_system_handler.py, tests/manager_tests/test_vulnerabilities_handler.py
=> VULN-1626 refactor(manager): unify multiple bools filter functionality

manager/report_handler.py, tests/manager_tests/test_report_handler.py
=> VULN-1671 Missing known exploit count for CVES per severity /executive

Dockerfile, Pipfile, Pipfile.lock, evaluator/evaluator.py, platform_mock/Pipfile.lock, scripts/pipenv-lock.sh, tests/Pipfile, tests/Pipfile.lock
=> fix(evaluator): use patched asyncpg version supporting sslrootcert until it's fixed upstream

build_deploy.sh, deploy/clowdapp.yaml, pr_check.sh
scripts needed for clowder deployment
=> chore: add pr_check and build_deploy scripts

Pipfile, Pipfile.lock, evaluator/evaluator.py, platform_mock/Pipfile.lock, tests/Pipfile, tests/Pipfile.lock
the exception is not handled inside asyncpg currently in current PR
state
=> fix(evaluator): validate the CA cert before sending to asyncpg

common/utils.py
=>  Fix(common): set patch access to false when access forbidden

deploy/clowdapp.yaml
=> fix(clowder): add real kafka values into clowder deployment

database/schema/upgrade_scripts/088-cyndi-fedramp-fix.sql, database/schema/ve_db_postgresql.sql, database/upgrade/dbupgrade.sh
=> fix(database): init cyndi on fresh db creation (non-container db)

listener/upload_listener.py
This reverts commit 8b807f586058ea99c657df562456e57e78a7d337.
=> VULN-1655 - Revert "feate(listener): add release version filtering"

deploy/clowdapp.yaml
MR to app-interface with switch to use ci-int jenkins has been merged, so we should be able to deploy insights engine in pr check
=> chore: deploy insights-engine as dependency

database/schema/upgrade_scripts/090-vmaas-sync-rule-mapping.sql, database/schema/ve_db_postgresql.sql, vmaas_sync/vmaas_sync.py
=> VULN-1794 fix(vmaas_sync): fix cve deletion

database/Dockerfile, database/Dockerfile.centos, run_tests.sh
Tested on local copy of CI database.
=> VULN-1674 feat(database): bump database to rhel8/centos8

manager/base.py, manager/cve_handler.py, manager/system_handler.py
=> VULN-1795 when OS is unknown, or not available use N/A

manager.spec.yaml, manager/system_handler.py, tests/manager_tests/schemas.py
=> VULN-1749 Return culled_timestamp  /systems AND /affected_systems

advisor_listener/advisor_listener.py, common/peewee_model.py, common/utils.py, database/schema/upgrade_scripts/091-add-rule-checksum.sql, database/schema/ve_db_dev_data.sql, database/schema/ve_db_postgresql.sql, tests/advisor_listener_tests/test_advisor_listener.py
=> VULN-1719 Skip unchanged system results in advisor-listener

Dockerfile, conf/manager.env, conf/manager_base.env, database/Dockerfile, database/Dockerfile.centos, database/schema/init_schema.sh, docker-compose.yml, manager.admin.spec.yaml, manager/admin_handler.py
=> VULN-1681 feat(manager_admin, database): add db admin queries for maintaining db

build_deploy.sh
=> chore: retag image built from master as latest

deploy/clowdapp.yaml, pr_check.sh
=> chore: run smoke tests in ephemeral env

common/config.py
=> fix(common): cast rbac_timeout env var to int

deploy/clowdapp.yaml
=> chore(metrics): drop s3 from clowder

manager.spec.yaml, manager/cve_handler.py, manager/filters.py, tests/manager_tests/schemas.py, tests/manager_tests/test_cve_handler.py
=> VULN-1826 feat(manager): unify rule_presence and rule_key for affected/mitigated

deploy/clowdapp.yaml, pr_check.sh
=> chore: run smoke tests using cji

advisor_listener/advisor_listener.py
=> VULN-1719 fix(advisor_listener): log skipped inventory ids

common/config.py
=> fix(clowder): use rds ca path

manager/vulnerabilities_handler.py
=> VULN-1813 Secondary sort key for CVEs

manager/list_view.py, manager/vulnerabilities_handler.py, tests/manager_tests/test_links.py
=> perf(manager): select total_count together with data in single query

Dockerfile
=> VULN-1841 fix: return common/ folder to dockerfile

deploy/clowdapp.yaml
=> fix(clowder): db name needs to match name of secret in stage env

database/upgrade/dbupgrade.sh, database/upgrade/upgrade.py, deploy/clowdapp.yaml, pr_check.sh
=> chore: enable cyndi in ephemeral env

Dockerfile, build_deploy.sh
=> chore: improve image build

advisor_listener/advisor_listener.py
=> VULN-1851 fix(advisor-listener): fix upload_data parsing for logger in parse_inventory_data()

.github/workflows/tests.yml, Dockerfile, listener/upload_listener.py
=> VULN-1852 Listener fails with traceback

.github/workflows/tests.yml, Dockerfile, tests/vmaas_sync_tests/test_vmaas_sync.py, vmaas_sync/vmaas_sync.py
=> Promote vmaas_sync fix to stable

database/schema/ve_db_dev_data.sql, manager.admin.spec.yaml, tests/manager_tests/conftest.py, tests/manager_tests/test_admin_handler.py, tests/manager_tests/vuln_testcase.py, tests/taskomatic_tests/test_db_metrics.py, tests/taskomatic_tests/test_delete_systems.py, tests/taskomatic_tests/test_taskomatic.py, tests/vmaas_sync_tests/test_vmaas_sync.py
=> test(manager_admin): add tests for manager admin

manager/list_view.py, manager/vulnerabilities_handler.py, tests/manager_tests/test_links.py
This reverts commit 09cf73dd29269982247a0e2b100547f237c9531b.
VULN-1846
/v1/systems times got better but /v1/vulnerabilities/cves times got worse
=> Revert "perf(manager): select total_count together with data in single query

tests/manager_tests/test_admin_handler.py
=> tests: add more manager admin tests

monitoring/grafana/dashboards/grafana-dashboard-clouddot-insights-vulnerability-engine.configmap.yml, taskomatic/jobs/db_metrics.py
=> chore: add useful metrics for monitoring account sizes

.coveragerc, tests/common_tests/test_bo_proxy.py, tests/common_tests/test_bounded_executor.py, tests/common_tests/test_failed_cache.py, tests/common_tests/test_status_app.py, tests/common_tests/test_utils.py
=> test: add common module unit tests

common/config.py, conf/taskomatic.env, deploy/clowdapp.yaml, taskomatic/taskomatic.py
=> feat(taskomatic): support running job on startup (useful for db_metrics job)

deploy/clowdapp.yaml
=> fix(clowder): manager admin is using default user from env

Dockerfile, advisor_listener/advisor_listener.py, common/peewee_model.py, database/schema/upgrade_scripts/092-add-system-cache.sql, database/schema/ve_db_postgresql.sql, evaluator/evaluator.py, manager/system_handler.py, tests/manager_tests/schemas.py
=> feat: store cached counts for systems

tests/metrics_tests/conftest.py, tests/metrics_tests/test_metrics_gather.py, tests/metrics_tests/test_stats_manager.py
=> test: add more metrics tests

deploy/clowdapp.yaml
=> build: add missing clowdapp configurations

manager/admin_handler.py, monitoring/grafana/dashboards/grafana-dashboard-clouddot-insights-vulnerability-engine.configmap.yml, taskomatic/jobs/db_metrics.py
=> chore: add number of missing systems in inventory to graph

deploy/clowdapp.yaml
=> fix(clowder): cyndi pipeline name

Dockerfile, Pipfile, Pipfile.lock, platform_mock/Pipfile.lock, tests/Pipfile, tests/Pipfile.lock
=> chore: asyncpg 0.24.0 has required SSL parameter functionality

listener/upload_listener.py, tests/listener_tests/test_upload_listener.py
=> test: add more listener tests

evaluator/evaluator.py
=> fix(evaluator): SSL params in asyncpg 0.24.0 work only using DSN

taskomatic/jobs/usage_metrics.py, tests/taskomatic_tests/test_usage_metrics.py
=> test: add taskomatic usage metrics tests

manager/filters.py, tests/manager_tests/test_cve_handler.py
=> chore(manager): change rule filter non-rule value to false

tests/evaluator_tests/test_evaluator.py
=> test: add more evaluator tests

taskomatic/taskomatic.py, tests/taskomatic_tests/test_taskomatic.py
=> test: add more taskomatic tests

deploy/clowdapp.yaml
workaround till patch is deployed by clowder - VULN-1870
=> fix(clowder): use PATCH_HOST for patch url

manager/system_handler.py, tests/manager_tests/schemas.py
=> feat(manager): enable cached cve counts

manager.spec.yaml
=> chore(manager): fix description for new rule filter

taskomatic/jobs/rules_git_sync.py
=> fix(taskomatic): catch collision with advisor_listener

common/config.py, conf/taskomatic.env, database/schema/upgrade_scripts/093-cve-account-cache.sql, database/schema/ve_db_postgresql.sql, deploy/clowdapp.yaml, taskomatic/jobs/cacheman.py, tests/taskomatic_tests/test_db_metrics.py
VULN-1864
Dynamically generate cache for accounts with >= 1000 systems every 5 mins. Detect when no system was evaluated since last cache generation.
=> feat(taskomatic): generate account-CVE cache periodically

run_tests.sh, taskomatic/taskomatic.py, tests/common_tests/conftest.py, tests/common_tests/test_utils.py, tests/evaluator_tests/test_evaluator.py, tests/taskomatic_tests/conftest.py, tests/taskomatic_tests/test_taskomatic.py, tests/vmaas_sync_tests/test_vmaas_sync.py
=> test: enable async tests and change tornado test to pytest

listener/upload_listener.py
=> feat(upload_listener): add release version lock filtering

build_deploy.sh
**TODO** delete webhook for stable image build
=> Deploy master to QA

taskomatic/jobs/cacheman.py
=> fix(taskomatic): fix error when more than one cve_id is deleted

taskomatic/jobs/cacheman.py
=> fix(taskomatic): deleted system should trigger cache refresh

taskomatic/jobs/cacheman.py
=> fix(taskomatic): join with inventory schema to ensure active systems

common/config.py, conf/manager_base.env, deploy/clowdapp.yaml, manager/base.py, manager/cve_handler.py, manager/system_handler.py
=> chore: drop CYNDI_ENABLED support

advisor_listener/advisor_listener.py, common/constants.py, common/utils.py, tests/advisor_listener_tests/test_advisor_listener.py, vmaas_sync/vmaas_sync.py
=> feat(advisor_listener): try to request vmaas for unknown cve data

common/config.py, deploy/clowdapp.yaml
=> feat(config): take SSL kafka parameters from clowder

pr_check.sh
=> chore: run advisories tests in pr_check

monitoring/grafana/dashboards/grafana-dashboard-clouddot-insights-vulnerability-engine-usage-metrics.configmap.yml, monitoring/grafana/dashboards/grafana-dashboard-clouddot-insights-vulnerability-engine.configmap.yml
=> chore: add usage metrics to dashboard

taskomatic/jobs/usage_metrics.py, tests/taskomatic_tests/test_usage_metrics.py
=> feat(taskomatic): add avg age metrics

manager.spec.yaml, manager/base.py, manager/cve_handler.py, manager/system_handler.py, tests/manager_tests/schemas.py
=> feat(manager): add advisory_available and remediation flags

deploy/clowdapp.yaml
so it won't override old service during migration
=> chore: temporarily remove proxy

deploy/clowdapp.yaml
=> fix(clowder): names have to be different

deploy/clowdapp.yaml
=> fix(clowder): replicas spec, turn on proxy

common/config.py, deploy/clowdapp.yaml
=> chore: remove PATCH_HOST workaround

deploy/clowdapp.yaml
=> chore: delete proxy

monitoring/grafana/dashboards/grafana-dashboard-clouddot-insights-vulnerability-engine.configmap.yml
=> chore: service names in grafana dashboard

common/status_app.py, entrypoint.sh, vmaas_sync/vmaas_sync.py
=> fix(manager): expose manager on metrics port as well

monitoring/grafana/dashboards/grafana-dashboard-clouddot-insights-vulnerability-engine-usage-metrics.configmap.yml
=> chore: add avg age grafana dashboard

evaluator/evaluator.py, vmaas_sync/vmaas_sync.py
=> fix: use simplier upsert and insert in same order to avoid deadlocks

manager.admin.spec.yaml, manager.spec.yaml, manager/admin_handler.py, manager/system_handler.py, tests/manager_tests/test_admin_handler.py, tests/manager_tests/test_readonly.py, tests/manager_tests/test_system_handler.py
=> feat(manager, manager_admin): move system deletion endpoint from manager

pr_check.sh
VULN-1948
you can use labels `skip-build`, `skip-deploy`, `skip-tests` ideally before clicking on Open PR button.
=> chore: use labels in pr_check

common/config.py, vmaas_sync/vmaas_sync.py
=> fix: vmaas_sync should write to evaluator_recalc_topic

pr_check.sh
=> chore: ignore failure when processing requirements

manager.spec.yaml, manager/base.py, manager/cve_handler.py, manager/main.py, manager/rbac_manager.py, manager/report_handler.py, manager/status_handler.py, manager/system_handler.py, manager/vulnerabilities_handler.py, tests/manager_tests/schemas.py, tests/manager_tests/test_rbac_manager.py, tests/manager_tests/test_report_handler.py, tests/manager_tests/vuln_testcase.py
=> feat(manager): implementation of RBAC

manager/rbac_manager.py, platform_mock/Dockerfile, platform_mock/platform_mock.py, tests/manager_tests/test_rbac_manager.py, tests/manager_tests/test_report_handler.py
=> feat(manager): rbac with inventory

monitoring/grafana/dashboards/grafana-dashboard-clouddot-insights-vulnerability-engine.configmap.yml
=> chore: remove metrics panel

listener/upload_listener.py
=> feat(listener): store empty system repos in vmaas_json

Dockerfile, common/peewee_model.py, database/schema/upgrade_scripts/097-last-status-change.sql, database/schema/ve_db_postgresql.sql, manager/cve_handler.py, manager/status_handler.py, taskomatic/jobs/cacheman.py
=> fix: trigger cache re-count on CVE status change

monitoring/grafana/dashboards/grafana-dashboard-clouddot-insights-vulnerability-engine-usage-metrics.configmap.yml
=> fix(monitoring): fix avg age metrics dashboard

common/config.py
=> fix: add evaluator_recalc_topic to legacy deployment config

.github/workflows/tests.yml, Dockerfile, database/schema/upgrade_scripts/099-vmaas-sync-delete-cache.sql, database/schema/ve_db_postgresql.sql
=> fix(vmaas-sync): add missing permission to delete CVE cache table

deploy/clowdapp.yaml
=> build: add backoffice secret to clowdapp.yaml

pr_check.sh
This reverts commit 4b165e1ea8c539c425111589ae8fd2e6f045437e.
it's fixed on inventory side
=> Revert "chore: workaround inventory issue"

manager/dashboard_handler.py, manager/playbook_handler.py, manager/rbac_manager.py, platform_mock/platform_mock.py, tests/manager_tests/schemas.py
=> feat(manager): add additional perms request for some endpoints

manager/system_handler.py
=> fix(manager): handle when opt_out call does not have valid rhaccount

pr_check.sh
=> chore: fix github labels in pr_check

advisor_listener/advisor_listener.py, tests/advisor_listener_tests/test_advisor_listener.py
=> fix crash and remove playbook count cache

advisor_listener/advisor_listener.py, common/config.py, common/mqueue.py, common/utils.py, common/vmaas_client.py, conf/advisor_listener.env, deploy/clowdapp.yaml, evaluator/evaluator.py, tests/advisor_listener_tests/conftest.py, tests/advisor_listener_tests/test_advisor_listener.py
=> perf: make advisor-listener async

pr_check.sh
depends on https://github.com/RedHatInsights/bonfire/pull/152
=> chore: keep pr_check namespace with label

manager/base.py
=> fix(manager): better check for non-existing account

common/config.py, conf/vmaas-sync.env, deploy/clowdapp.yaml, vmaas_sync/vmaas_sync.py
=> feat(vmaas_sync): introduce flag for disabling sync on start

common/config.py
=> fix(common): use db variables from deployment if available

common/config.py, common/database_handler.py
=> refactor(common): simplify db variables

pr_check.sh
=> chore: run more tests in ephemeral

.github/workflows/tests.yml, Dockerfile, manager/rbac_manager.py
=> fix(manager): request only opt_out:read on systems endpoint

manager/system_handler.py, manager/vulnerabilities_handler.py
=> fix(manager): set default sort key for status and business_risk

Dockerfile, build_deploy.sh, docker-compose.yml, platform_mock/Dockerfile, pr_check.sh
=> use postgresql pkg from RHEL/CentOS

advisor_listener/advisor_listener.py, common/utils.py
=> fix(advisor-listener): create asyncpg function for checking existing system

manager/list_view.py
=> fix(manager): always sort by default key when available

pr_check.sh
=> chore: update labels processing in pr_check

manager/status_handler.py
missing where clause for account
VULN-2076
=> chore(manager): optimize status update query

manager.spec.yaml
=> chore(manager): add rbac error schema to api spec

manager/rbac_filters.py, manager/rbac_manager.py, manager/system_handler.py, tests/manager_tests/test_rbac_manager.py
=> feat(manager): add rbac filters for default behaviour of endpoint

manager.spec.yaml, manager/system_handler.py, tests/manager_tests/test_readonly.py, tests/manager_tests/test_system_handler.py
=> chore(manager): remove deprecated opt_out PATCH endpoint

deploy/clowdapp.yaml
VULN-2099
Drop the systems which does not have business risk set to any value.
=> chore: reduce the size of floorist dump

deploy/clowdapp.yaml
=> chore: don't set empty secret in ephemeral env

manager/base.py, manager/cve_handler.py, manager/system_handler.py, manager/vulnerabilities_handler.py
=> fix(manager): fix csv support for ids endpoint

Dockerfile
=> chore: Used CentOS 8 Stream in Dockerfile (Centos 8 EOL)

advisor_listener/advisor_listener.py
=> perf(advisor-listener): reduce number of updated unchanged rows

deploy/clowdapp.yaml
=> fix: bump resources section in deployment for floorist job

platform_mock/Dockerfile
=> fix: Update URLs for resources of platform-mock.

database/schema/upgrade_scripts/101-add-business-risk-critical.sql, database/schema/ve_db_postgresql.sql, tests/manager_tests/test_business_risk.py
=> feat: Add 'Critical' option for business risk

manager/base.py
=> fix(manager): calling Request.handle_errors(...) will lost '_endpoint_name'

pr_check.sh
=> chore(pr_check): run all smoke tests

manager/vulnerabilities_handler.py
=> fix: 500 POST /vulnerabilities/cves, cve_list == \x00

monitoring/grafana/dashboards/grafana-dashboard-clouddot-insights-vulnerability-engine-usage-metrics.configmap.yml
=> fix: grafana usage metrics dashboard

common/peewee_model.py, database/schema/upgrade_scripts/102-add-announcement.sql, database/schema/ve_db_postgresql.sql, manager.admin.spec.yaml, manager.spec.yaml, manager/admin_handler.py, manager/announcement_handler.py, tests/manager_tests/test_admin_handler.py, tests/taskomatic_tests/test_db_metrics.py
=> feat: APIs for setting, deleting & getting announcements

manager.spec.yaml, manager/dashbar_handler.py, tests/manager_tests/test_dashbar_handler.py
=> feat(manager): add dashbar endpoint

deploy/clowdapp.yaml
=> IQE-1363 make insights-engine optionalDependency

database/schema/ve_db_dev_cyndi.sql, platform_mock/Pipfile, platform_mock/Pipfile.lock, platform_mock/platform_mock.py
=> chore(platform-mock): fix system profile parsing

manager/admin_handler.py
=> fix: Announcement deletion

common/peewee_model.py, database/schema/upgrade_scripts/103-rules-account-cache.sql, database/schema/ve_db_postgresql.sql, manager/dashboard_handler.py, taskomatic/jobs/cacheman.py, tests/taskomatic_tests/test_db_metrics.py
=> perf: dashboard api optimization

Dockerfile, taskomatic/jobs/cacheman.py
=> chore: bump minimal schema in image

manager/report_handler.py
=> perf(manager): use cached rules in exec report

manager/dashbar_handler.py, tests/manager_tests/test_dashbar_handler.py
=> fix(dashbar): dashbar should respect mitigation reason

platform_mock/Dockerfile
Pipenv does not work without `python` symlink.
=> fix(platform_mock): create symlink to python

deploy/clowdapp.yaml
VULN-2251
Memory ratio on stage changed to 2, now limit / request = 2.
=> chore: bump floorist memory request

pr_check.sh
=> chore(pr_check): don't run tests which need patch app

taskomatic/jobs/rules_git_sync.py
=> fix: cve_rule_mapping self repair

manager/status_handler.py
=> fix(manager): filter out edge systems when changing CVE status

common/config.py
=> chore(clowder): translate EVALUATOR_TOPIC using Clowder dict

monitoring/grafana/dashboards/grafana-dashboard-clouddot-insights-vulnerability-engine-usage-metrics.configmap.yml
=> Fix: do not show decimals in grafana usage metrics dashboard

manager/report_handler.py
=> fix: Sorting in executive_report top_cves

Dockerfile, common/config.py, database/Dockerfile, database/Dockerfile.centos, database/upgrade/dbupgrade.sh, database/upgrade/upgrade.py, deploy/clowdapp.yaml, platform_mock/entrypoint.sh, run_tests.sh
- Also setup notificator pwd on stage vault
=> chore(clowder): deploy notificator service

notificator/notificator_queue.py
Also, info, does not need to be escaped anymore.
=> chore(notificator): move notificator context to events section

manager.admin.spec.yaml, manager/admin_handler.py
=> feat(manager-admin): add endpoint for deleting notified tuples

advisor_listener/advisor_listener.py, common/utils.py, evaluator/evaluator.py, tests/advisor_listener_tests/test_advisor_listener.py
=> feat(adivsor_listener): start sending tuples to notificator

advisor_listener/advisor_listener.py, common/peewee_model.py, database/schema/upgrade_scripts/105-add-org-id.sql, database/schema/ve_db_dev_data.sql, database/schema/ve_db_postgresql.sql, deploy/clowdapp.yaml, listener/upload_listener.py, manager/base.py, manager/cve_handler.py, manager/status_handler.py, manager/system_handler.py, taskomatic/jobs/cacheman.py, taskomatic/jobs/db_metrics.py, taskomatic/jobs/usage_metrics.py
=> feat: add_org_id

common/peewee_model.py, manager/base.py, manager/cve_handler.py, manager/gunicorn_conf.py, manager/status_handler.py, manager/system_handler.py, scripts/3scale-mock
=> feat(manager): try to use org_id if available

common/utils.py, evaluator/evaluator.py
=> fix(evaluator): check if account number is in message

platform_mock/Pipfile, platform_mock/Pipfile.lock
=> fix(platform-mock): add asyncpg to platform mock

conf/taskomatic.env, database/schema/upgrade_scripts/106-delete-notif-taskomatic.sql, database/schema/upgrade_scripts/107-notif-accounts-index.sql, database/schema/ve_db_postgresql.sql, deploy/clowdapp.yaml, taskomatic/jobs/delete_notifications.py, tests/taskomatic_tests/test_delete_notifications.py
=> feat(taskomatic): add old notifications cleanup job

notificator/notificator.py, notificator/notificator_queue.py
=> feat(notificator): add more cve metadata to notifications payload

advisor_listener/advisor_listener.py, common/utils.py, listener/upload_listener.py, tests/advisor_listener_tests/test_advisor_listener.py, tests/listener_tests/test_upload_listener.py, vmaas_sync/vmaas_sync.py
=> org_id listener, advisor_listener, payload tracker

notificator/notificator_queue.py
=> chore(notificator): log skipped potential notification

notificator/notificator_queue.py
=> chore(notificator): log sent/repeated notifications

evaluator/evaluator.py
=> perf(evaluator): get sys_vulns ids from cache for updates

advisor_listener/advisor_listener.py
=> perf(advisor_listener): get sys_vulns ids from original select

evaluator/evaluator.py
=> perf(evaluator): perform update/insert only once per system

advisor_listener/advisor_listener.py, common/utils.py, evaluator/evaluator.py, notificator/notificator.py, notificator/notificator_queue.py, tests/advisor_listener_tests/test_advisor_listener.py, tests/evaluator_tests/test_evaluator.py, tests/notificator_tests/test_notificator.py, tests/notificator_tests/test_notificator_queue.py
=> Send org_id to notifications

common/config.py, conf/manager_base.env, database/schema/upgrade_scripts/109-notificator-manager.sql, database/schema/ve_db_postgresql.sql, deploy/clowdapp.yaml, manager.admin.spec.yaml, manager/admin_handler.py, notificator/app.py, notificator/notificator.py, notificator/notificator_queue.py, tests/manager_tests/test_admin_handler.py, tests/notificator_tests/conftest.py, tests/notificator_tests/test_app.py, tests/notificator_tests/test_notificator.py, tests/notificator_tests/test_notificator_queue.py
=> feat: notificator in-memory cache refresh

pr_check.sh
=> chore: prevent RBAC resources from being removed

Pipfile, Pipfile.lock, common/config.py
=> add managed kafka more sasl mechanism support

manager/announcement_handler.py
=> fix: 204 code when no announcement is set

manager/base.py
=> chore(manager): better catch and log waiting for cyndi

deploy/clowdapp.yaml
Migrate ClowdApp floorist job and ConfigMap to `FloorPlan` Custom Resource.
`FloorPlan` is handled by [Floorist Operator](https://github.com/RedHatInsights/floorist-operator).
=> chore: migrate floorist to FloorPlan CR

notificator/notificator_queue.py
=> chore(notificator): add metric for # of sent notifications

manager.spec.yaml, manager/cve_handler.py, manager/system_handler.py, tests/manager_tests/schemas.py
=> feat: additional parameters to /ids endpoints

monitoring/grafana/dashboards/grafana-dashboard-clouddot-insights-vulnerability-engine.configmap.yml
=> feat(grafana): show sent notifications count

notificator/notificator_queue.py
=> feat(notificator): add display name and inventory id to msg

manager.spec.yaml, manager/cve_handler.py, tests/manager_tests/schemas.py
=> feat: /cves affected_but_not_vulnerable count

Dockerfile, advisor_listener/advisor_listener.py, database/schema/upgrade_scripts/110-account_number-null.sql, database/schema/ve_db_postgresql.sql, listener/upload_listener.py
=> fix: allow empty account_number

common/config.py
=> fix(kafka): support PLAIN sasl mechanism

deploy/clowdapp.yaml
=> fix: add custom chunksize for floorplan

deploy/clowdapp.yaml
=> fix: half chunksize for floorist

deploy/clowdapp.yaml
=> fix: half floorist chunksize

listener/upload_listener.py, tests/listener_tests/test_upload_listener.py
=> feat(listener): add basearch to vmaas json

deploy/clowdapp.yaml
=> fix: increase floorist chunksize

manager/status_handler.py
=> feat: Include affected but not vulnerable CVEs in /vulnerabilities/status API

manager/cve_handler.py
=> fix(manager): fix abnv count in /cve/{cve_id} endpoint

manager/dashboard_handler.py
=> feat(dashboard): Include affected but not vulnerable CVEs in /vulnerabilities/dashboard API

manager/dashbar_handler.py
=> feat(dashbar): Include affected but not vulnerable CVEs in /vulnerabilities/dashbar API

manager/report_handler.py
=> feat(report_handler): Include affected but not vulnerable CVEs

manager/base.py
=> feat(base): Include rules for affected but not vulnerable CVEs in base.py

common/config.py, conf/manager_base.env, conf/vmaas-sync.env, deploy/clowdapp.yaml, docker-compose.devel.yml, docker-compose.yml, manager.admin.spec.yaml, manager/admin_handler.py, tests/vmaas_sync_tests/test_vmaas_sync.py, vmaas_sync/vmaas_sync.py
=> refactor(vmaas-sync): change to cronjob

taskomatic/jobs/cacheman.py
=> fix(taskomatic): disable cache for an account also when there are no cached data

manager/system_handler.py, tests/manager_tests/test_system_handler.py
=> feat: Include affected but not vulnerable CVEs in /vulnerabilities/systems/{inventory_id}/cves

manager.spec.yaml, manager/playbook_handler.py
=> feat(playbook): add reboot_required for playbooks

evaluator/evaluator.py
=> fix(evaluator): skip advisor-only systems when it's scheduled for re-evaluation

.github/workflows/tests.yml, Dockerfile.test, platform_mock/platform_mock.py
=> chore(platform_mock): add org_id to platform mock

evaluator/evaluator.py
=> feat(evaluator): add abnv counts to system cve cache

notificator/notificator_queue.py
=> feat(notificator): send notifications for abnv systems

manager.spec.yaml, manager/cve_handler.py, manager/system_handler.py, tests/manager_tests/schemas.py
=> feat: add remediation field to .../ids endpoints

manager/status_handler.py
=> fix(status_handler): dont count partial rule passes as hit

manager/system_handler.py
=> fix(system_handler): dont count partial rule passes as hit

manager/vulnerabilities_handler.py
=> fix(vuln_handler): dont count partial rule passes as hit

manager/dashbar_handler.py
=> feat(dashbar): dont count partial rule passes as hit

manager/report_handler.py
=> fix(report_handler): corrected abnv query

manager/cve_handler.py
=> fix(cve_handler): dont count partial rule passes as hit

manager/dashboard_handler.py
=> feat(dashboard): dont count parial rule passes as hit

advisor_listener/advisor_listener.py
=> feat(advisor_listener): add abnv counts to system cve cache

advisor_listener/advisor_listener.py
=> fix(advisor_listener): count cve when rule is not active

advisor_listener/README.md
=> docs(advisor_listener): document RV of parse_inventory_data

manager/base.py
=> refactor(base): get_rules_for_cves query refactoring

manager/filters.py
=> fix(manager): cve rule filter should filter between abnv and hits

.github/workflows/tests.yml
=> chore: use postgres14 in unit tests

common/peewee_model.py, database/schema/upgrade_scripts/112-add-insights_needs_reboot.sql, database/schema/ve_db_postgresql.sql, taskomatic/jobs/rules_git_sync.py
=> feat: store all playbooks & insights need reboot fact

common/peewee_conditions.py, manager/dashbar_handler.py, manager/dashboard_handler.py
=> refactor(manager): unify manager conditions

common/peewee_model.py, database/schema/upgrade_scripts/113-rule_autoplaybook.sql, database/schema/ve_db_postgresql.sql, taskomatic/jobs/rules_git_sync.py
=> feat: process automatic playbook rule

advisor_listener/README.md, evaluator/README.md, listener/README.md, vmaas_sync/README.md
=> chore: add docs

.github/workflows/db-docs.yml
=> chore: replace deprecated set-output command

README.md, notificator/README.md
=> chore: add notificator and overall docs

common/peewee_conditions.py, manager/admin.py, manager/admin_handler.py, manager/announcement_handler.py, manager/api_status_handler.py, manager/base.py, manager/cve_handler.py, manager/dashbar_handler.py, manager/dashboard_handler.py, manager/filters.py, manager/gunicorn_conf.py, manager/list_view.py, manager/playbook_handler.py, manager/rbac_manager.py, manager/report_handler.py, manager/risk_handler.py, manager/status_handler.py, manager/system_handler.py, manager/version_handler.py, manager/vulnerabilities_handler.py, tests/manager_tests/test_business_risk.py, tests/manager_tests/test_status_handler.py
=> chore(manager): common manager queries

evaluator/evaluator.py, tests/evaluator_tests/test_evaluator.py
=> VULN-2519: don't send  empty repository_list or package_list to vmaas

Dockerfile, common/config.py, common/mqueue.py, conf/grouper.env, deploy/clowdapp.yaml, docker-compose.devel.yml, docker-compose.yml, entrypoint.sh, grouper/grouper.py, platform_mock/entrypoint.sh
=> feat: introduce kafka message partitioner

manager.spec.yaml, manager/system_handler.py, tests/manager_tests/schemas.py
=> feat: /systems/{inv_id}/cves generate_autoplaybook field

README.md
=> docs: document running unit tests locally

database/schema/upgrade_scripts/114-add_advisories_column.sql, database/schema/ve_db_postgresql.sql
=> feat(database): add advisories column to system_vulnerabilities

deploy/clowdapp.yaml
According to https://github.com/RedHatInsights/pdf-generator/blob/main/INTEGRATION.md#enable-crc-pdf-generator-as-a-dependency
This will enable us to use the new backend PDF generation services. 
=> chore(clowdapp): Add crc-pdf-generator to as optional dependency

common/config.py
=> fix: strtobool returns int

database/schema/upgrade_scripts/115-truncate_inactive_partition.sql, database/schema/ve_db_postgresql.sql
=> chore: truncate inactive partition to improve evaluation performance

common/peewee_database.py, common/peewee_model.py, manager/main.py
=> fix(manager): actually use read replica

manager/base.py
=> fix(manager): DB_READ_REPLICA connection should be closed during initialization

database/schema/upgrade_scripts/117-system_platform_indexes.sql, database/schema/upgrade_scripts/118-system_vulnerabilities_indexes.sql, database/schema/ve_db_postgresql.sql
=> perf: add indexes to system_platform table

evaluator/evaluator.py
=> chore(evaluator): remove dead branch

common/peewee_conditions.py, manager/status_handler.py
=> feat: change conditions for non-edge systems

Pipfile, Pipfile.lock, common/config.py, common/paging.py, common/vmaas_client.py, manager/admin_handler.py, manager/rbac_manager.py, platform_mock/Pipfile, platform_mock/Pipfile.lock, tests/Pipfile, tests/Pipfile.lock, tests/manager_tests/test_admin_handler.py
=> feat(fedramp): use tls for outgoing connections

deploy/clowdapp.yaml
=> chore: try use index on floorist query

deploy/clowdapp.yaml
=> fix(deploy): admin is mounted by default

common/peewee_conditions.py, manager/base.py
=> fixing bugs caused by null or empty string account_number

cluster/cluster.py
Using the `pg_repack` we can achieve the same results without completely locking the tables.
=> feat(cluster): use pg_repack and reindex

common/config.py, deploy/clowdapp.yaml
=> fix(config): kafka ssl should be chosen by clowder

monitoring/grafana/dashboards/grafana-dashboard-clouddot-insights-vulnerability-engine.configmap.yml
=> chore(grafana): adjust grafana graphs for new listener and evaluator

taskomatic/jobs/stale_systems.py
=> feat(stale_systems): delete systems which should be culled

listener/processor.py, tests/listener_tests/test_processor.py
=> fix(listener): fix timestamps and more log

.github/workflows/tests.yml
=> chore(github-actions): use current version of codecov

common/peewee_model.py, database/schema/upgrade_scripts/121-resolution_type.sql, database/schema/ve_db_postgresql.sql, manager.spec.yaml, manager/playbook_handler.py, taskomatic/jobs/rules_git_sync.py
=> feat: add resolution_type for playbooks

deploy/clowdapp.yaml, listener/queue.py
=> chore: better logging for new pipeline

listener/listener.py
=> chore(listener): add signal handlers

listener/processor.py
=> fix(listener): correctly check inventory_msg type

listener/common.py, listener/listener.py, listener/processor.py, listener/queue.py, tests/conftest.py, tests/listener_tests/conftest.py, tests/listener_tests/test_processor.py
=> feat(listener): move asyncpg to psycopg

deploy/clowdapp.yaml, evaluator/evaluator2.py
=> chore: limit number of  concurrent messages

evaluator/logic.py
=> chore(evaluator): load rule cache from reserved connection

listener/listener.py, listener/queue.py, tests/listener_tests/test_listener.py, tests/listener_tests/test_queue.py
=> fix(listener): unlock on message errors

advisor_listener/advisor_listener.py, common/config.py, common/utils.py, conf/common.env, deploy/clowdapp.yaml, listener/listener.py, listener/upload_listener.py, platform_mock/platform_mock.py, tests/common_tests/test_utils.py, tests/listener_tests/test_upload_listener.py
=> fix(rhsm): use list of allowed reporters instead of checking insights_id

advisor_listener/advisor_listener.py, common/utils.py, evaluator/evaluator.py, evaluator/processor.py, listener/advisor_processor.py, listener/inventory_processor.py, listener/processor.py, listener/upload_listener.py, manager/gunicorn_conf.py, notificator/notificator.py, notificator/notificator_queue.py, tests/advisor_listener_tests/test_advisor_listener.py, tests/evaluator_tests/test_evaluator.py, tests/notificator_tests/test_notificator.py, tests/notificator_tests/test_notificator_queue.py, vmaas_sync/vmaas_sync.py
=> feat: remove account number remains in listener

monitoring/grafana/dashboards/grafana-dashboard-clouddot-insights-vulnerability-engine.configmap.yml
=> chore(grafana): add new metrics for grouper and listener

common/utils.py, evaluator/processor.py, listener/common.py, listener/inventory_processor.py
=> chore(evaluator): correctly new cves to notificator

database/schema/ve_db_dev_data.sql, manager/dashbar_handler.py, manager/dashboard_handler.py, manager/report_handler.py, manager/vulnerabilities_handler.py, pr_check.sh, tests/manager_tests/test_dashbar_handler.py, tests/manager_tests/test_dashboard_handler.py, tests/manager_tests/test_manager.py, tests/manager_tests/test_report_handler.py, tests/manager_tests/test_vulnerabilities_handler.py, vmaas_sync/vmaas_sync.py
=> feat: sync unfixed CVEs

database/schema/upgrade_scripts/122-vulnerable_package_tables.sql, database/schema/ve_db_postgresql.sql, tests/taskomatic_tests/test_db_metrics.py
=> feat(database): add tables to store unfixed vulnerabilities

evaluator/processor.py
=> chore(evaluator): use only system_vulnerabilities_active partition

manager.admin.spec.yaml, manager/admin_handler.py
=> feat(manager_admin): add truncation endpoint for sv_inactive

grouper/common.py, grouper/queue.py, listener/advisor_processor.py, listener/common.py, listener/inventory_processor.py, listener/listener.py
=> chore: add more counters to the new listener

common/utils.py, deploy/clowdapp.yaml, grouper/common.py, grouper/queue.py, listener/advisor_processor.py, listener/inventory_processor.py
=> various fixes

.github/workflows/tests.yml, Dockerfile, Dockerfile.test, common/utils.py, evaluator/evaluator2.py, evaluator/processor.py, grouper/queue.py, listener/advisor_processor.py, listener/inventory_processor.py, listener/listener.py, platform_mock/Dockerfile
=> payload tracker and error logging fixes

manager/rbac_manager.py
[RHINENG-606](https://issues.redhat.com/browse/RHINENG-606)
=> fix: unknown groups resource

advisor_listener/advisor_listener.py, common/config.py, common/identity.py, conf/common.env, deploy/clowdapp.yaml, listener/common.py, listener/listener.py, listener/upload_listener.py, manager/base.py, tests/listener_tests/test_upload_listener.py, tests/manager_tests/test_manager.py
=> fix(rhsm): don't check insights entitlement

evaluator/logic.py
=> fix: advisory is available with manually fixable cve

evaluator/logic.py
=> fix(evaluator): make sure DB state is saved before adding item to cache

advisor_listener/advisor_listener.py, grouper/grouper.py, listener/advisor_processor.py, listener/common.py, listener/inventory_processor.py, listener/listener.py, listener/upload_listener.py, tests/listener_tests/test_upload_listener.py
VULN-2694
I hope that `url` is present in the message from rhsm reporter
=> fix(rhsm): don't expect platform_metadata

deploy/clowdapp.yaml, evaluator/common.py, evaluator/logic.py, evaluator/processor.py
=> re-enable writing vulnerability state if not set + logging improvements

common/utils.py, listener/advisor_processor.py, listener/inventory_processor.py, tests/common_tests/test_utils.py, tests/listener_tests/test_upload_listener.py
=> refactor(listener): improve skipping of msgs from excluded reporters

vmaas_sync/vmaas_sync.py
=> fix(vmaas-sync): check presence of cve in vulnerable_package_cve table before deletion

Dockerfile, common/peewee_model.py, database/schema/upgrade_scripts/124-advisory_available_cache.sql, database/schema/ve_db_postgresql.sql, manager.spec.yaml, manager/vulnerabilities_handler.py, taskomatic/jobs/cacheman.py, tests/manager_tests/schemas.py
- filter arg is available, but does nothing until selects from unfixed vulnerabilities tables are added
=> feat(manager): return advisory_available from /vulnerabilities/cves API

platform_mock/Dockerfile, platform_mock/entrypoint.sh
=> chore(platform_mock): bump kafka

deploy/clowdapp.yaml
=> chore: add apiPath to bind API to correct path

evaluator/logic.py
=> fix(evaluator): some caching and deadlock issues

manager/feature_handler.py, manager/rbac_manager.py
=> fix(cves_without_errata): use toggle_cves_without_errata permission

manager.admin.spec.yaml, manager/admin_handler.py
=> feat(manager_admin): allow rule key to be deleted using API

deploy/clowdapp.yaml
=> chore(cluster): run weekly, not daily

manager.spec.yaml, manager/base.py, manager/cve_handler.py, manager/filters.py, tests/manager_tests/schemas.py, tests/manager_tests/test_cve_handler.py
=> CVE handler - filter inventory groups

manager/base.py
=> fix: corrected condition for caching

manager.spec.yaml, manager/vulnerabilities_handler.py, tests/manager_tests/schemas.py
=> Vulnerabilities handler - filter inventory groups

common/utils.py, manager.spec.yaml, manager/base.py, tests/manager_tests/schemas.py
null - don't display any UI elements
false - display UI elements to enable FF, hide advisory_available filter
true - display UI elements to disable FF, show advisory_available filter
=> fix(manager): make cves_without_errata nullable to indicate global disable

README.md, platform_mock/platform_mock.py, scripts/generate_insights_archive.py
=> Dev setup fixes

platform_mock/platform_mock.py
=> chore(platform-mock): make reporter configurable

manager/base.py, manager/dashbar_handler.py, manager/dashboard_handler.py, manager/rbac_manager.py, manager/vulnerabilities_handler.py, tests/manager_tests/test_rbac_manager.py
=> system groups fixes

manager/rbac_manager.py, tests/manager_tests/test_rbac_manager.py
=> fix: RBAC parsing fix

manager/filters.py
=> docs(manager): add docstrings to inventory group filters

manager.spec.yaml, manager/base.py, manager/cve_handler.py, manager/filters.py, manager/system_handler.py, manager/vulnerabilities_handler.py, tests/manager_tests/schemas.py, tests/manager_tests/test_cve_handler.py, tests/manager_tests/test_system_handler.py
=> fix(manager): remove ungrouped_hosts parameter

evaluator/common.py, evaluator/logic.py, listener/advisor_processor.py
=> fix(evaluator): use rule hits details object

tests/manager_tests/test_cve_handler.py
=> test: call function

common/config.py, common/feature_flags.py
Fixes URL to Unleash server as well as the authorization token use.
RHINENG-1773
=> fix(common): feature flags connection

taskomatic/jobs/cacheman.py, taskomatic/taskomatic.py, tests/manager_tests/conftest.py
Count edge systems in within cacheman if `vulnerability.edge_parity` feature flag is enabled.
=> feat: cacheman to count edge systems

common/constants.py, manager.spec.yaml, manager/cve_handler.py, manager/filters.py, tests/manager_tests/schemas.py, tests/manager_tests/test_cve_handler.py
Will work after #1491 gets merged.
I will also alter the tests after the merge.
RHINENG-1640
=> feat(manager): implement new host_type filter for affected_systems

common/constants.py, manager.spec.yaml, manager/base.py, manager/filters.py, manager/vulnerabilities_handler.py, tests/manager_tests/schemas.py, tests/manager_tests/test_vulnerabilities_handler.py
=> feat(manager): count edge systems in vulnerabilities/cves and add filter

manager/filters.py
=> fix(manager): affecting filter should take edge systems into account

manager/dashbar_handler.py
=> chore(manager): return cves_without_errata flag in dashbar meta

manager/vulnerabilities_handler.py
=> fix(manager): fix of a distinct count, need to do in more complicated way

manager/cve_handler.py, manager/system_handler.py, manager/vulnerabilities_handler.py
=> fix(manager): display all CVEs when no advisory_available filter is specified

manager.spec.yaml
<Edited the summary and description sections. Added a use case to each description>.
=> <docs>: Updates to Vulnerability Management API

manager/vulnerabilities_handler.py
fixes bug when all CVEs with 0 affecting systems are displaing Advisory Available
VULN-2789
=> fix(manager): check static advisory list instead of default true

manager/filters.py, manager/vulnerabilities_handler.py
=> fix(manager): fix the condition to show unfixed CVEs in current env

manager/vulnerabilities_handler.py
=> fix(manager): re-introduce bool_or to avoid CVE duplication

manager/filters.py, tests/manager_tests/test_vulnerabilities_handler.py
=> fix(manager): include cves without cvss score in cvss filter

manager/base.py
=> fix(manager): verify that cached groups and fetched groups have same type

listener/listener.py
=> fix(listener): raise InvalidAdvisorMsg which will be catched

manager/dashbar_handler.py, manager/dashboard_handler.py, manager/report_handler.py
=> fix(manager): display only fixed cves 

common/utils.py
=> fix(evaluator): always set none remediation for rule hits without playbook

manager/cve_handler.py, manager/system_handler.py, tests/manager_tests/test_cve_handler.py, tests/manager_tests/test_system_handler.py
=> feat(manager): systems sortable by groups

manager/vulnerabilities_handler.py
=> fix(manager): advisory_available flag in unfixed only query

manager/cve_handler.py, manager/system_handler.py
=> fix(manager): fix sorting by fields in cves/ids endpoint

manager/filters.py
=> fix(manager): fix inventory filters query

tests/scripts/vmaas_mock.py, vmaas_sync/vmaas_sync.py
=> fix(vmaas_sync): use new last change timestamp for repo based evaluation

pr_check.sh
=> Re enable dashboard and report tests in pr check

manager.spec.yaml, manager/feature_handler.py
=> feat(manager): allow customer to delete his received notifications

manager/filters.py, tests/manager_tests/test_cve_handler.py
=> feat(manager): return RPMDNF systems by default from affected_systems

manager.spec.yaml, manager/cve_handler.py, tests/manager_tests/schemas.py, tests/manager_tests/test_cve_handler.py
=> feat(manager): add overall affected systems count to /cve/id

deploy/clowdapp.yaml, poetry.lock
=> feat: enable cyndi filters on ephemeral

manager/cve_handler.py
=> fix(manager): fix print

common/feature_flags.py
=> fix(manager): randomize unleash tmp path for each gunicorn process

manager.spec.yaml, manager/base.py, manager/report_handler.py, tests/manager_tests/schemas.py, tests/manager_tests/test_report_handler.py
=> feat(manager): executive report to feature system count by host types

manager.spec.yaml, manager/dashboard_handler.py, manager/report_handler.py, manager/vulnerabilities_handler.py, tests/manager_tests/schemas.py, tests/manager_tests/test_dashboard_handler.py, tests/manager_tests/test_report_handler.py
=> feat(manager): introduce NA score CVEs in endpoints

evaluator/common.py, evaluator/evaluator.py, evaluator/processor.py, grouper/queue.py, vmaas_sync/vmaas_sync.py
=> feat(evaluator): skip old kafka evaluation messages

manager/base.py
=> fix(manager): allow UI referer to be other envs

Dockerfile, common/peewee_model.py, database/schema/upgrade_scripts/130-edge_cache.sql, database/schema/upgrade_scripts/131-drop-systems_affected.sql, database/schema/ve_db_postgresql.sql, manager/base.py, manager/filters.py, manager/vulnerabilities_handler.py, taskomatic/jobs/cacheman.py
=> feat: start count edge separately into caches

manager/dashbar_handler.py, manager/dashboard_handler.py, manager/report_handler.py
=> fix(manager): start using new cache on other endpoints

scripts/gabi/cve_stats.py
=> chore: add gabi script collecting cve stats

manager.spec.yaml, manager/vulnerabilities_handler.py, tests/manager_tests/schemas.py
=> feat(manager): add system_count_per_type counts in /vulnerabilities/cves

manager/main.py
=> fix(manager): use limiter only in 3scale proxy calls

deploy/clowdapp.yaml
=> fix: 'yupana' is going to be deprecated in favor of 'satellite' and 'discovery'

manager/dashbar_handler.py, manager/dashboard_handler.py, manager/report_handler.py
=> fix(manager): return query after applying where to make it work

manager/gunicorn_conf.py, scripts/3scale-mock
=> service account minor fix

Jenkinsfile
=> Add CRCD secrets

deploy/clowdapp.yaml
=> fix(floorist): try to run with chunksize to lower memory requirements

common/config.py
=> feat: support multiple kafka brokers

common/feature_flags.py, develfeatureflags.json, manager/base.py, manager/cve_handler.py, manager/dashbar_handler.py, manager/dashboard_handler.py, manager/report_handler.py, manager/vulnerabilities_handler.py, taskomatic/jobs/cacheman.py, tests/manager_tests/test_cve_handler.py, tests/manager_tests/test_dashbar_handler.py, tests/manager_tests/test_dashboard_handler.py, tests/manager_tests/test_manager.py, tests/manager_tests/test_report_handler.py, tests/manager_tests/test_vulnerabilities_handler.py
=> feat: delete edge_parity feature flag

README.md, pyproject.toml
=> chore: update dev setup info in README

poetry.lock, pyproject.toml
poetry also updates other packages which are not pinned RHINENG-7857
=> chore(deps): update aiohttp to fix cve

manager/base.py, manager/cve_handler.py, manager/filters.py, manager/main.py, manager/system_handler.py, manager/vulnerabilities_handler.py, taskomatic/jobs/cacheman.py, tests/manager_tests/vuln_testcase.py
=> Inherit global CVE status

Jenkinsfile, ci/functions.sh
=> Fix artifact collection on tests failure

common/peewee_database.py
=> chore: log there are missing secrets for read replica

common/peewee_model.py
=> fix(manager): set specific models for possible RW operations instead of changing peewee internals

entrypoint.sh, manager/main.py, tests/manager_tests/conftest.py
=> fix(manager): uvicorn worker overrides gunicorn logging settings

database/schema/upgrade_scripts/132-add-vulnerable_package_cve-index.sql, database/schema/ve_db_postgresql.sql
=> fix(database): vulnerable_package_cve(cve) index is useful for cve/affected_systems query

.github/workflows/safety.yml, .github/workflows/tests.yml, Dockerfile, Dockerfile.test, docker-compose.test.yml, docker-compose.yml, platform_mock/Dockerfile, scripts/devel-compose
=> chore: Centos 8 Stream was removed, install postgresql from COPR

common/logging.py
=> fix: include levelname in CW logs from python code

Dockerfile
=> fix(build): update it-root-ca

tests/scripts/vmaas_mock.py, vmaas_sync/vmaas_sync.py
=> feat(vmaas_sync): Recalc system with updated packages in repos

security-scan.sh
Adding the Security Scanning Workflow. This script will provide the same level of support as the standard PlatSec GitHub Workflow.
A copy of the [security-scan-source-template.sh](https://github.com/RedHatInsights/platform-security-gh-workflow/blob/master/jenkins/security-scan-source-template.sh) has been added to this repo, and the (GitHub) `platsec-gh-vulnerability-scan` Jenkins Job has be added to the Vulnerability-Engine `build.yml` in App-Interface.
Similar to the standard GitHub Workflow, we can accommodate feature requests and provide updates on the fly and with full transparency. The `security-scan-source-template.sh` script, which sources the main [security-scan.sh](https://github.com/RedHatInsights/platform-security-gh-workflow/blob/master/jenkins/security-scan.sh) script, …
=> Adding Security-Scan Script to Enable Jenkins Security Scan Job

common/logging.py
=> fix: string formatting in CloudWatch

vmaas_sync/vmaas_sync.py
=> fix: updated_package_names in vmaas sync

vmaas_sync/vmaas_sync.py
=> fix: udpated_repos keyerror in vmaas-sync

tests/scripts/vmaas_mock.py, vmaas_sync/vmaas_sync.py
Additional work needs to be done, reverting the change to not block release to prod.
RHINENG-10107
RHINENG-10893
This reverts commit a776d33be63e166b3cff93a68248bd15af6fe1a6. This reverts commit 97e9354a5953b949b15e4d07c408a07983e45272. This reverts commit d8cef5a5b3b373bb0761481bfbdbff78580cbc1d. This reverts commit 8422f755e34a99b321fcaf99d06a527d6a3feae4.
=> fix(vmaas_sync): Revert recalc system with updated packages in repos

manager/cve_handler.py, manager/status_handler.py, manager/system_handler.py, poetry.lock
=> fix(manager): add missing DISTINCTs

evaluator/logic.py
=> fix(evaluator): limit number of linked vulnerable packages to a system

database/schema/upgrade_scripts/134-cve_account_data_idx.sql, database/schema/ve_db_postgresql.sql
=> fix: add cve_account_data rh_account_id index

evaluator/common.py, evaluator/logic.py, evaluator/processor.py
=> chore: extend evaluation metrics

monitoring/grafana/dashboards/grafana-dashboard-clouddot-insights-vulnerability-engine.configmap.yml
=> chore: add grafana dashboard for evaluation duration metrics

manager.spec.yaml
=> fix(manager): advisory detail is never returned

common/constants.py, evaluator/common.py, evaluator/evaluator.py, evaluator/logic.py, evaluator/processor.py, grouper/queue.py, vmaas_sync/vmaas_sync.py
=> recalc optimization

monitoring/grafana/dashboards/grafana-dashboard-clouddot-insights-vulnerability-engine.configmap.yml
=> chore: add new evaluator skipped metrics

evaluator/processor.py
=> chore: measure loading system profile duration

monitoring/grafana/dashboards/grafana-dashboard-clouddot-insights-vulnerability-engine.configmap.yml
=> chore: fix RDS metrics and system count graph

develfeatureflags.json, evaluator/README.md, evaluator/logic.py, evaluator/processor.py
=> perf(evaluator): re-evaluations should handle only CVEs with errata (as they are triggered by errata release)

monitoring/grafana/dashboards/grafana-dashboard-clouddot-insights-vulnerability-engine.configmap.yml
=> chore: split some evaluator graphs to upload and recalc

evaluator/processor.py
=> fix(evaluator): JSONB column doesn't need to be parsed here

evaluator/processor.py
=> fix(evaluator): missing await

evaluator/processor.py
=> fix(evaluator): skip by message timestamp only in recalcs, recalcs are not full evaluations like uploads

evaluator/processor.py
=> fix(evaluator): compare offset-aware datetimes

vmaas_sync/vmaas_sync.py
=> fix(vmaas-sync): make sure event row is commited before sending it in kafka messages

Jenkinsfile, deploy/clowdapp.yaml
=> chore(ephemeral): remove --no-remove-resources

Dockerfile, Dockerfile.test, database/upgrade/dbupgrade.sh, deploy/clowdapp.yaml, entrypoint.sh, platform_mock/Dockerfile, platform_mock/entrypoint.sh
=> chore: use ubi9

evaluator/logic.py
RHINENG-12773
```
2024-09-23 11:18:45,405:INFO:evaluator.logic:attempting to get data from VMAAS
2024-09-23 11:18:45,501:ERROR:common.vmaas_client:Error during request to VMaaS endpoint http://vmaas-webapp-go.vmaas-stage.svc:8000/api/vmaas/v3/cves/: HTTP 405, {"type": "about:blank", "title": "Method Not Allowed", "detail": "Method Not Allowed", "status": 405}
2024-09-23 11:18:45,502:ERROR:evaluator.logic:error importing from VMAAS
2024-09-23 11:18:45,508:ERROR:__main__:new row for relation "cve_metadata" violates check constraint "cve_metadata_cve_check"DETAIL: Failing row contains (153343461, , unknown, 0, null, null, null, null, null, null, null, null, null, null, null).'Traceback (most recent call last):\n File "/engine/common/utils.py", line 390, in _log\n task.result()\n File …
```
=> fix: handle error when inserting empty cve name into db

renovate.json
=> chore: automerge PRs updating konflux references

vmaas_sync/vmaas_sync.py
=> fix(vmaas-sync): return only repositories having advisories since the last modified_since

manager/base.py, manager/gunicorn_conf.py, manager/playbook_handler.py, manager/rbac_manager.py, manager/system_handler.py, platform_mock/platform_mock.py, scripts/3scale-mock, tests/manager_tests/test_rbac_manager.py
=> RHINENG-13409 - implement System identity auth

pyproject.toml
going to enable Konflux image build only for tags
=> ci: create patch tag for more keywords

Dockerfile
=> Reduce container layers
