examples/kafka_consumer.py, examples/kafka_producer.py
- consumer and producer scripts for message queue running in remote `vmaas-ci` OpenShift project
- usage:
1.     $ oc login
2.     $ oc project vmaas-ci
3. forward kafka port from OpenShift pod to localhost:
$ oc port-forward kafka-1-6-268rj 29092:29092
4. point `kafka-1.vmaas-ci.svc` hostname to `127.0.0.1` in your `/etc/hosts`
5. install dependency:
$ pip install confluent-kafka
6. run listener:
$ python examples/kafka_consumer.py
7. write to message queue
$ python examples/kafka_producer.py
=> example scripts to consume message queue and write to it

.env, .gitignore, docker-compose.devel.yml, listener/reposcan_listener.py
- run vmaas and vuln-engine on same docker network
- identify webapp and listener connections and send confirmation to listener once all webapps are refreshed
see also https://github.com/RedHatInsights/vmaas/pull/409
=> notify listener when all webapps are refreshed

manager/common.py, manager/cve_handler.py, manager/vulnerabilities_handler.py, scripts/3scale-mock, scripts/README.md
This adds 3scale support to manager. 
It also provides a 3scale-mock command line tool for locally testing.  To use it, simply prefix the curl command you would use to hit the local system with the 3scale-mock script.  For example:
./3scale-mock curl -k -X GET https://localhost:8300/api/v1/cves/CVE-2014-0160/affectedsystems/ | python -m json.tool
Run 3scale-mock --help for other options and commands ('curl' is a command, as is 'print' and 'save').
./3scale-mock save        <-- will write a default identity to ~/.3scale-mock
If ~/.3scale-mock exists, it will use it's contents for the identity sent to the server.  If not, it uses the identity defined in the 3scale-mock script itself.
A few values in the identity can be overridden on the command line for easier testing.  See 3scale-mock …
=> add 3scale support

Dockerfile-apidoc, Dockerfile-manager, conf/apidoc.env, docker-compose.yml, manager/common.py, manager/cve_handler.py, manager/main.py, manager/vulnerabilities_handler.py
This PR creates Swagger UI container for vulnerability-engine-manager APIs. As these are to be rewritten (pagination, filtering) it would be nice to have swagger already in place as this will happen.
=> create apidoc skeleton for future usage in manager

scripts/openshift-rsync.sh
Requires OpenShift container in devel mode (`./scripts/openshift-devel-container.sh`).
Examples:
Copy evaluator dir from git to OpenShift container and finish:
```
$ ./scripts/openshift-rsync.sh evaluator
```
Continuously keep OpenShift container synced with changes in git:
```
$ ./scripts/openshift-rsync.sh evaluator -w
```
=> add helper script to copy data from git into openshift container

scripts/3scale-mock
this is needed for example when uploading new archive:
./3scale-mock curl -k -F "upload=@insights-ibm-x3650m4-03-vm04.lab.eng.brq.redhat.com-20181108112209-6.9.tar.gz;type=application/vnd.redhat.vulnerability.something+tgz" -H 'x-rh-insights-request-id: 52df9f748eabcfea' https://upload-service-vulnerability.192.168.42.14.nip.io/api/v1/upload
=> workaround to quote more strings

manager/vulnerabilities_handler.py
When multiple systems have different sources of vulnerabilities the counting breaks like this due to way how the data is grouped. E.g.:
count |      cve      |  name  | cvss3_score |  impact   |      public_date       
-------+---------------+-------+-------------+-----------+------------------------
1 | CVE-2016-0800 | RULES |       5.900 | Important | 2016-03-01 00:00:00+00
6 | CVE-2016-0800 | VMAAS |       5.900 | Important | 2016-03-01 00:00:00+00
If any of the for same cve has source RULES, then they should take precedence in the source and the counts should be added together.
E.g. like this:
count |      cve      |  name  | cvss3_score |  impact   |      public_date       
-------+---------------+-------+-------------+-----------+------------------------
7 | CVE-2016-0800 | RULES | …
=> fix counting of vulnerable systems with different sources

Dockerfile-evaluator, Dockerfile-manager, evaluator/entrypoint.sh, manager/entrypoint.sh, wait-for-postgres.sh
Fixes issue where we are not waiting for start of PostgreSQL in some services which leads to following errors like:
vulnerability-engine-evaluator | Traceback (most recent call last):
vulnerability-engine-evaluator |   File "/evaluator/evaluator.py", line 337, in <module>
vulnerability-engine-evaluator |     main()
vulnerability-engine-evaluator |   File "/evaluator/evaluator.py", line 332, in main
vulnerability-engine-evaluator |     evaluator = QueueEvaluator(kafka_host, kafka_port, [kafka_evaluator_topic, kafka_rules_results_topic], kafka_group_id)
vulnerability-engine-evaluator |   File "/evaluator/evaluator.py", line 51, in __init__
vulnerability-engine-evaluator |     self.conn = DatabaseHandler.get_connection()
vulnerability-engine-evaluator |   File …
=> Fix #73 - wait for PostgreSQL in services depending on it

evaluator/evaluator.py
Fixes following error during cve_metadata import
vulnerability-engine-evaluator | Traceback (most recent call last):
vulnerability-engine-evaluator |   File "/evaluator/evaluator.py", line 373, in <module>
vulnerability-engine-evaluator |     main()
vulnerability-engine-evaluator |   File "/evaluator/evaluator.py", line 369, in main
vulnerability-engine-evaluator |     evaluator.run()
vulnerability-engine-evaluator |   File "/evaluator/evaluator.py", line 327, in run
vulnerability-engine-evaluator |     self._sync_cve_md()
vulnerability-engine-evaluator |   File "/evaluator/evaluator.py", line 174, in _sync_cve_md
vulnerability-engine-evaluator |     cvss2_score = float(cves[cve]['cvss2_score']) if 'cvss2_score' in cves[cve] else None
vulnerability-engine-evaluator | ValueError: could not …
=> fix import of cvss2_score and cvss2_metrics

evaluator/evaluator.py
Support for syncing only CVEs issued by Red Hat has been merged in VMAAS (https://github.com/RedHatInsights/vmaas/pull/437), use that functionality to sync rh cves only.
When rh_only is passed to older instances of vmaas they ignore it and do not crash.
=> sync Red Hat issued CVEs only

database/init_schema.sh
not needed anymore due to changes in bb879759a31da1bb5745cf813e490e5efffef5de
=> remove db_dev_data from schema initialization script

manager/system_handler.py, manager/vulnerabilities_handler.py
in the cvss_score field we sometimes return cvss3_score if it's available and sometimes cvss2 if v3 is not available, as there's no simple indicator (apart from looking whether cvss3_score is null or not) like field which version is returned
as we return both cvss2_score and cvss3_score the 'cvss_score' field is not needed as it returns mismash
=> don't return mishmash of cvss scores

Dockerfile-listener
as we're using insights-core from pip there's no need to install dnf plugins and enable @vmaas/libs
=> remove obsolete container dependencies

manager/rule_handler.py
Added new api call to get all rule details for a system.
I think the previous two calls can be removed, but I'll leave them in for now.
New api call is
/r/insights/platform/vulnerability/v1/rules/<inventory_id>/details
NOTE: this call requires inventory_id, not insights_id as used in most of our other api that require the system identifier.
Results look like this:
{
"inventory_id": "fb0820e7-18c1-4a8c-a78a-901faef7fbe2",
"rule_ids": {
"CVE_2017_5715_cpu_virt|VIRT_CVE_2017_5715_CPU_3_ONLYKERNEL": {
"affected_amd_family": false,
"cves_fail": [
"CVE-2017-5715"
],
"cves_pass": [],
"error_key": "VIRT_CVE_2017_5715_CPU_3_ONLYKERNEL",
"kernel_pkg_name": "kernel",
"type": "rule"
},
"CVE_2017_5753_4_cpu_kernel|KERNEL_CVE_2017_5753_4_CPU_ERROR_3": {
"cves_fail": [
"CVE-2017-5715"
],
"cves_pass": [ …
=> add support to get all rule details for a system

Dockerfile-listener, Dockerfile-listener.rhel7, listener/listener.py, scl-enable.sh
- using Python 3.6 from SCL
- both CentOS 7 and RHEL 7 Dockerfiles
- RHEL 7 Dockerfile requires Docker host/OpenShift platform with valid subscription
TODO:
- convert other services
- change e2e templates to build from RHEL Dockerfile on prod
=> base listener on CentOS and RHEL

Dockerfile-listener, Dockerfile-listener.rhel7
In dev environment, OpenShift default SCC causes pod to run as some random UID in a set range of UIDs.  It is overriding our attempt to run as user 'insights'.  We were installing the pip modules with "--user" arg, so other users weren't able to access the libs.  In minishift env, pod runs as user 'insights', so we didn't see the issue.
Dockerfiles are now changed to run pip install as root and without "--user" arg so all user have access to the installed libs.
This is part of VMAAS-225
=> Change to pip install as root so any user can access the libs

evaluator/evaluator.py
This to prevent log messages about "can't find inventory_id in db" because rules-engine is sending back insights system id, not inventory_id.
=> stop kicking off rules-engine processing

manager/cve_handler.py, manager/system_handler.py
Accessible from :
```
curl http://MACHINE:8300/r/insights/platform/vulnerability/v1/cves/CVE-2019-000666/affected_systems | python -m json.tool
{
"meta": {...},
"data": [
{
"type": "system",
"id": "inventory-01",
"attributes": {
"inventory_id": "inventory-01",
"status_id": 2,
"status_name": "On-Hold",
"satellite_managed": false
}
}
]
}
```
AND
```
curl http://MACHINE:8300/r/insights/platform/vulnerability/v1/systems | python -m json.tool
{
"data": [
{
"attributes": {
"inventory_id": "inventory-01",
"satellite_managed": false,
"cve_count": 1
},
"id": "inventory-01",
"type": "system"
}
],
"meta": {...}
}
```
=> VMAAS-270 : expose satellite_managed to the API

.pre-commit-config.yaml, requirements.txt, scripts/github-fetch-pullrequest, setup.cfg
Adds pre-commit config (and fixes Python 3 compatibility).
Once https://github.com/RedHatInsights/vulnerability-engine/pull/173 is merged I'll add `pre-commit` to `requirements.txt`.
Then it will be ready to run `pre-commit run --all-files`, create PR with all changes and merge it so everyone can start working on reformatted files without rebasing their code a lot.
Also will require fixing lot of issues found by flake8 (line length etc.)
=> pre-commit + Python 3 compatibility

common/peewee_model.py, database/ve_db_dev_data.sql, database/ve_db_postgresql.sql, evaluator/evaluator.py, manager/cve_handler.py, manager/system_handler.py, manager/test/test.py
this PR adds new 'last_evaluation' column for all systems, defaults to NULL, after each evaluation this timestamp is updated
this affects following manager APIs:
- `/r/insights/platform/vulnerability/v1/systems/` - systems with NULL 'last_evaluation' are not included in the list
- `/r/insights/platform/vulnerability/v1/systems/<inventory_id>/cves` - returns 404 if inventory_id either doesn't exist in DB or last_evaluation is NULL for given inventory_id
- `/r/insights/platform/vulnerability/v1/cves/<cve_name>/affected_systems` - adds 'last_evaluation' field for systems in the list
this needs an review if this is correct
=> VMAAS-314 - add 'last_evaluation' timestamp and don't display not evaluated systems

manager/system_handler.py
opted_out systems are already handled in `get_cves` function, on the line `142` there's an if which throws 404 before this query is called which ensures that `opt_out` is always `False`.
=> simplify query by removing redundant condition

Dockerfile-evaluator, Dockerfile-evaluator.rhel7, Dockerfile-listener, Dockerfile-listener.rhel7, Dockerfile-platform-mock, Dockerfile-vmaas-sync, Dockerfile-vmaas-sync.rhel7
Previously we were adding our code before running e.g. pip install or other things which are changing less often and have bigger layers than our code.
I've restructured the Dockerfiles in a way that things that are changing the least and take the biggest amount of time are run first, and our code is added at last possible place so we won't run whole `pip install --upgrade && pip install $LOT_OF_STUFF` after one line of code gets changed.
=> reduce number of intermediate Docker images after code change

manager/status_handler.py, tests/manager_tests/test_manager.py
Now that pytests use postgresql, submitting unit-test coverage for status
=> Add unit-tests for status-handler

database/schema/init_schema.sh
To support database upgrade, the admin user (ve_db_admin) must have CREATEROLE attribute so it is able to create new roles in upgrade scripts.  The 003-...sql upgrade script needs this support.
This PR will cause the admin user to have the CREATEROLE attribute.  If the vulnerability-engine-database image is updated and deployed where the database already exists, it will still ensure the admin user is modified with the CREATEROLE attribute.
In the alternative, one can attach to the database container an issue the alter user command manually...
In the UI, go to the terminal for the running database pod and issue this command:
**psql -c "ALTER USER ve_db_admin WITH CREATEROLE" -d vulnerability**
Or from the command line, exec to the container and run bash, then issue the above command: …
=> Make sure admin user has createrole attribute

Dockerfile-evaluator, Dockerfile-evaluator.rhel7, Dockerfile-listener, Dockerfile-listener.rhel7, Dockerfile-manager, Dockerfile-manager.rhel7, Dockerfile-vmaas-sync, Dockerfile-vmaas-sync.rhel7, requirements-evaluator.txt, requirements-listener.txt, requirements-manager.txt, requirements-vmaas-sync.txt
Dockerfiles modified to pip install from requirements-xxx.txt files where xxx is component.  These requirements file specify explicitly the versions of the python libs to be installed.
Previously we would install libraries that resulted in several dependencies getting installed as well.  All the dependencies have been added to the requirements file with specific versions as well.
=> use fixed versions of python libraries in requirements-xxx.txt files

.coveragerc, .travis.yml, database/schema/upgrade_scripts/001-db-upgrade-support.sql, database/upgrade/upgrade.py, requirements.txt, run_tests.sh, tests/database_tests/test_upgrade.py, tests/utils.py
1. setup 2 databases (old schema, new schema) with dev_data
2. upgrade the old one and compare schema only dumps
By default it will upgrade DB from a3388e0b8643e7b022947fb2c0c2f862ef0056b0 to schema from current branch. If you want to test upgrade with between different schemas, you can specify commits in `UPGRADE_FROM` and `UPGRADE_TO` env variables
=> Add upgrade test

listener/archive_parser.py
This reverts commit 3bda28dfa8c08f09284408d1171ff447fb53f90c.
Due to bug in insights-core get_max function.
=> Revert "only evaluate latest version of each package"

listener/upload_listener.py, requirements-listener.txt, requirements.txt, tests/listener_tests/test_upload_listener.py
Listener should only send eval-messages on new systems or systems whose
vmaas_json is different than the last time we saw them.
=> Make listener selective about giving work to evaluator

vmaas_sync/vmaas_sync.py
This addresses VMAAS-457 and also ensures a new connection will be established following each time vmaas-sync checks for systems that need to be re-evaluated.
=> change to named cursor when querying db for systems to reevaluate

manager.spec.yaml
Adds x-methodName to api spec. This is then used by @redhat-cloud-services/vulnerabilities-client as a name of a method.
=> Add x-methodName to apiSpec

database/schema/upgrade_scripts/010-add-repo-tables.sql, database/schema/ve_db_postgresql.sql, listener/upload_listener.py, requirements-listener.txt, requirements.txt, tests/data/truncate_dev_data.sql, tests/listener_tests/test_upload_listener.py
Store data about system's repositories in database tables (repo and system_repo) to enable racalculating based on updated repos only. This will be implemented in the next step.
=> Add repo and system_repo tables

wait-for-services.sh
fixes regression caused by #363 - KAFKA_HOST is now in common env file and is propagated to containers which don't use it - manager => wait-for-services never finishes
=> check if kafka lib is installed, skip if not

listener/upload_listener.py, tests/listener_tests/test_upload_listener.py
- don't do a delete from `repo` table, the query is slow to be executed after for every processed archive, append values only
- there is only up to 4000 repo label in RHSM, it can be cached in memory
- #380 helps to ignore custom repos which are useless because VMaaS can't evaluate them
=> don't delete from main repo table and use cache for repo IDs

common/utils.py
If you start vulnerability-engine while vmaas is not running it's waiting for VMaaS websocket, which comes online earlier before webapp which leads to tone of tracebacks like this:
```
vulnerability-engine-vmaas-sync | Websocket server is unavailable - sleeping
vulnerability-engine-vmaas-sync | Checking if Kafka server is up
vulnerability-engine-vmaas-sync | Everything is up - executing command
vulnerability-engine-vmaas-sync | 66610a6b9502 2019-07-18 07:37:41,596:INFO:common.logging:CloudWatch logging disabled
vulnerability-engine-vmaas-sync | 66610a6b9502 2019-07-18 07:37:41,596:INFO:__main__:Starting VMaaS sync service.
vulnerability-engine-vmaas-sync | 66610a6b9502 2019-07-18 07:37:41,602:INFO:__main__:Syncing CVE metadata
vulnerability-engine-vmaas-sync | 66610a6b9502 2019-07-18 …
```
=> wait a bit before retrying request

Dockerfile.test
Fedora 27 has PostgreSQL 9.6 while Fedora 29 has PostgreSQL 10 and we're
running PG 10 in production (and the code is written with PG 10) syntax
which was causing some issues in the tests (dbupgrade test mainly)
=> base test container on Fedora 29

manager/system_handler.py
In [PR#393](https://github.com/RedHatInsights/vulnerability-engine/pull/393) was a problem, when system was opted out and requested the list of CVEs, metadata returned wrong number of _total_items_ (should be 0 when opted out).
=> Fix opted out systems returned wrong number of items

evaluator/evaluator.py, tests/evaluator_tests/test_evaluator.py
fixing bug caused by #379 
> 2019-07-29 11:50:49,697:ERROR:common.utils:Future <Future at 0x7f414639feb8 state=finished raised RuntimeError> hit exception: 'Traceback (most recent call last):\n  File "/evaluator/common/utils.py", line 49, in on_thread_done\n    future.result()\n  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/_base.py", line 425, in result\n    return self.__get_result()\n  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result\n    raise self._exception\n  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File "/evaluator/evaluator/evaluator.py", line 290, in process_upload_or_re_evaluate\n …
=> propagate event loop to successfuly send webhooks message

evaluator/evaluator.py, tests/evaluator_tests/test_evaluator.py
- when_mitigated timestamp is incorrectly updated each evaluation
- affected systems count cache is incorrectly decremented each evaluation
=> fix incorrect mitigation

manager.spec.yaml, manager/cve_handler.py, tests/manager_tests/schemas.py
adding new field `systems_status_detail` (can be renamed if you have better idea how to name it) when fetching single CVE detail
first iteration, may be changed later
example
```
./scripts/3scale-mock -a 123456 curl -H "Content-Type: application/vnd.api+json" -X GET "http://localhost:8300/api/vulnerability/v1/cves/CVE-2018-18690"
```
```
{
"data": {
"attributes": {
"business_risk": "Not Defined",
"business_risk_id": 0,
"business_risk_text": null,
"cvss2_metrics": null,
"cvss2_score": null,
"cvss3_metrics": null,
"cvss3_score": null,
"description": "unknown",
"impact": "NotSet",
"modified_date": null,
"public_date": null,
"redhat_url": null,
"secondary_url": null,
"status": "Not Reviewed",
"status_id": 0,
"status_text": null,
"synopsis": "CVE-2018-18690",
"systems_status_detail": {
"0": 1, …
```
=> display systems counts for each status

manager/cve_handler.py, manager/status_handler.py
I have noticed that there are some 500 returned in PATCH operations when the nullable parameters are actually NULL, because of missing attribute in python object.
=> Fix return 500 when string is NULL in PATCH operations

listener/upload_listener.py
`
vulnerability-engine-listener | 2fef32284d0b 2019-09-24 14:26:44,813:ERROR:common.utils:Future <Future at 0x7fc8f2e5c198 state=finished raised TypeError> hit exception: 'Traceback (most recent call last):\n  File "/listener/common/utils.py", line 50, in on_thread_done\n    future.result()\n  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/_base.py", line 425, in result\n    return self.__get_result()\n  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result\n    raise self._exception\n  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File "/listener/listener/upload_listener.py", line 329, in process_upload\n    if …
=> Fix none type traceback in listener

manager/base.py, tests/manager_tests/test_manager.py
Remove duplication of error handling code between different request base classes.
DataError is now handled, and does not fall through to general Exception case. 
To resolve: Do we want to return `str(exc)` for DataError or provide a custom message, since they could possibly disclose information from the database ?
=> Unify error handling between different request handlers, handle database errors

.travis.yml, Dockerfile.dbdocs, docker-compose-dbdocs.yml, scripts/db_docs_generator.sh, scripts/schemaspy.properties
The same for vulnerability engine from [vmaas](https://github.com/RedHatInsights/vmaas/pull/612).
Only difference in the scripts are the ve folders paths and that the postgres service in travis must be stopped because the 5432 port is taken by postgresql.service, the service is started up after generation.
=> Add dbdocs generator and dockerfiles for it

scripts/openshift-debugger/Dockerfile, scripts/openshift-debugger/debugger.yml
other containers don't have psql, tar etc. and it's difficult to do any debugging from them
this container could be deployed in a project to do some basic debugging (not deployed automatically)
=> chore: add debugging service

manager/base.py, tests/manager_tests/test_manager.py
other apps use 10,20,50,100
vulnerability uses 10,25,50,100
=> fix(manager): change default page size to 20

metrics/Dockerfile
Docker builds are failing due to .txt files no longer existing in the 'metrics' dir
=> Fix: metrics dockerfile failing due to missing .txt files

metrics/s3_bucket_manager.py
QE found an issue when metrics runs against an empty S3 bucket.  This only happens the first time metrics is run in an environment, after that the bucket will always contain something.  This fixes the error.
=> fix: fix error when bucket is empty

docker-compose-dbdocs.yml, scripts/db_docs_generator.sh
There was wrong database dockerfile choosed, since the refactorization of engine. So it could not generate a documentation for db.
=> fix(dbdocs): fix generating bug for db docs

.travis.yml, Dockerfile.test, advisor_listener/Dockerfile, evaluator/Dockerfile, listener/Dockerfile, manager/Dockerfile, metrics/Dockerfile, platform_mock/Dockerfile, scripts/openshift-debugger/Dockerfile, taskomatic/Dockerfile, vmaas_sync/Dockerfile
This reverts commit be12c55b310edf2c97104a2ecaa315c86dfa6386.
=> chore: Revert "disable pipenv check because pyup.io is down"

advisor_listener/advisor_listener.py
When creating new record in system_vulnerabililies insert into
when_mitigated to make sure evaluator corretly handles situation where
new CVE appears first in advisor listener and then in evaluator.
With inactive rules evaluator and when_mitigated set to NULL evaluator
thinks that this CVE has been previously processed by it and does not
update CVE count caches accordingly.
Additionally for inactive rules and cases where VMaaS says that the CVE
is not applicable it creates short period of false positivity untill
when_mitigated is set by evaluator.
=> fix(advisor_listener): don't cause VMaaS hits with inactive rules

common/utils.py
The Payload Tracker is transitioning to using the new "request_id" terminology instead of the legacy "payload_id." This renames that field.
=> Update payload_id to request_id

Dockerfile.test, advisor_listener/Dockerfile, evaluator/Dockerfile, listener/Dockerfile, manager/Dockerfile, metrics/Dockerfile, platform_mock/Dockerfile, scripts/openshift-debugger/Dockerfile, taskomatic/Dockerfile, vmaas_sync/Dockerfile
https://github.com/pypa/pipenv/issues/4188
PIPENV_PYUP_API_KEY= can be removed when pipenv-2020.X.X is released
=> chore: pipenv check workaround

advisor_listener/advisor_listener.py, common/peewee_model.py, conf/listener.env, conf/taskomatic.env, database/schema/upgrade_scripts/059-deleted_table_removal.sql, database/schema/ve_db_dev_data.sql, database/schema/ve_db_postgresql.sql, evaluator/evaluator.py, listener/upload_listener.py, manager/cve_handler.py, manager/report_handler.py, manager/status_handler.py, manager/system_handler.py, metrics/metrics_gather.py, platform_mock/platform_mock.py, scripts/inventory_sync.py, taskomatic/jobs/cache_check.py, taskomatic/jobs/delete_systems.py, taskomatic/jobs/stale_systems.py, tests/data/truncate_dev_data.sql, tests/listener_tests/test_upload_listener.py, vmaas_sync/vmaas_sync.py
problems with current implementation:
- there is no guarancy that system is correctly imported or deleted when it's deleted shortly after upload
- listener and advisor-listener check deleted_systems table but it doesn't have any effect because other thread/pod can delete the system imediately after they check it
- there are orphaned systems in DB but missing in inventory
fix:
- remove deleted_systems table, use only system_platform for better insert/delete concurrency handling
- do not remove immediately, remember for 24h and remove by taskomatic
=> fix concurrent system import/delete

manager.spec.yaml, manager/cve_handler.py, tests/manager_tests/schemas.py, tests/manager_tests/test_cve_handler.py
CVE with 17105 systems affected.
```
[02/Jun/2020:06:43:58 +0000] 200 GET /api/vulnerability/v1/cves/CVE-2019-11745/affected_systems/ids 0.503558s
[02/Jun/2020:06:44:12 +0000] 200 GET /api/vulnerability/v1/cves/CVE-2019-11745/affected_systems 3.004704s
```
On the backend side the calculation is 6 times faster.
```
[tkasparek vulnerability-engine-fork] (just_ids_api)$ time ./scripts/3scale-mock curl -X GET http://localhost:8300/api/vulnerability/v1/cves/CVE-2019-11745/affected_systems/ids?page_size=99999 > /dev/null
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  735k  100  735k    0     0  1459k      0 --:--:-- --:--:-- --:--:-- 1456k
real	0m0.550s
user	0m0.035s
sys	0m0.012s
[tkasparek …
```
=> create API for retrieving only IDs of systems affected by CVE

evaluator/evaluator.py
54c934fea3088c8ac09ba73802e578e7256e9fa8 changed behavior
unmitigated_cves_ids.add(system_cves_map[cve]['cve_id'])
-                    if system_cves_map[cve]['rule_id'] is None:  # unmitigated only if there wasn't rule hit before
+                    if system_cves_map[cve]['active_rule']:  # unmitigated only if there wasn't rule hit before
inc_cves_ids.add(system_cves_map[cve]['cve_id'])
system_cves_map[cve]['rule_id'] is None
meant that rule wasn't present for the system CVE
system_cves_map[cve]['active_rule']
means that rule is existing for the system CVE, which inverted the
condition
=> fix(evaluator): use correct condition for increasing CVE counts

conf/settings.local.yaml, scripts/run_integration_tests.sh
1. Login to quay.io
2 ./scripts/run_integration_tests.sh
- script will stop currently running docker-compose, rebuild images with VMAAS_HOST set to prod, download the latest iqe-tests image from quay, and execute integration tests (except for basic_auth, e2e, and csaw tests)
**Importatnt:** To avoid 401s to JIRA, you need to provide your JIRA credentials in conf/settings.local.yaml (used for skipping tests which are blocked by an opened bug)
It looks like the evaluation is not working correctly when vulnerability is not connected to websocket (maybe due to CVE sync?), so you might need to start vmaas and sync CVEs
=> chore: script for running integration tests locally

wait-for-services.sh
VULN-620: when listener (and others) DB password contains newline, it is not properly set to DB user
=> fix: strip newline from DB password

manager.spec.yaml, manager/base.py, manager/cve_handler.py, manager/filters.py, manager/system_handler.py, manager/vulnerabilities_handler.py, tests/manager_tests/schemas.py, tests/manager_tests/test_cve_handler.py, tests/manager_tests/test_system_handler.py, tests/manager_tests/test_vulnerabilities_handler.py
Because the UI wants to use checkboxes for filtering rules and we are using one parameter for multiple operations, we need to split it in two parameters.
- `security_rule` parameter is only used for filtering rules errkeys (data type: array of strings (errkeys))
- `rule_presence` parameter is only used for rule presence boolean (data type: array of booleans (support for checkboxes when request come as true,false; true; etc...)
=> feat(manager): split rule errkey and rule presence filtering

manager.spec.yaml, manager/cve_handler.py, manager/system_handler.py, tests/manager_tests/schemas.py
'updated' sort parameter behaves similarly like 'last_upload', but the information about 'last_upload' is taken from Cyndi.
When Cyndi is disabled, it behaves just like 'last_upload'.
=> feat(manager): add 'updated' sort parameter

database/schema/init_schema.sh
Database roles are now created with our ve_db_admin user, not postgres.
=> fix(database): change database init

manager/base.py
probably because whole inventory.hosts table needs to be casted sequentialy when selecting single system
=> fix(manager): casting to TEXT on inventory.hosts may be very slow

Dockerfile, manager.admin.spec.yaml, manager.spec.yaml, manager/base.py, manager/main.py, scripts/turnpike-mock, tests/manager_tests/test_readonly.py, tests/manager_tests/test_refresh_handler.py, tests/manager_tests/vuln_testcase.py
- preparation for Turnpike integration
- added turnpike-mock wrapper usable same as 3scale-mock
- no authorization here, when request hits API, we expect Turnpike validated that user is in 'vulnerability-admins' group
- /admin/api/vulnerability/ is not exposed in 3scale
=> feat(manager): move current admin calls to path accessible using Turnpike

docker-compose.devel.yml, docker-compose.yml, entrypoint.sh, manager/admin.py, manager/base.py, manager/main.py, tests/manager_tests/test_readonly.py, tests/manager_tests/test_refresh_handler.py, tests/manager_tests/vuln_testcase.py
because it's not possible to make Swagger UI work with /admin/api/vulnerability here and /api/vulnerability in turnpike proxy
I was unsuccesful with setting connexion to serve openapi.json with fixed url
=> fix(manager-admin): split admin functionality to separate container

entrypoint.sh
Please feel free to close the PR if it's not suitable for the project. 
However, the "watchers" in the frontend are extremely useful (so it might be for the backend) cause you don't have to kill the process every single time but instead it reloads when the code changes. 
https://docs.gunicorn.org/en/19.0/settings.html#reload
=> chore: reload workers when code changes

manager/cve_handler.py, manager/filters.py, manager/list_view.py, manager/system_handler.py, manager/vulnerabilities_handler.py, tests/manager_tests/test_links.py
also changes:
* improving performance by avoiding calling distinct (required by CveRuleMapping join)
* fixed bug when SQL query is executed twice
* improved performance by splitting into subqueries and joining the result
* remove show all filter function as it can be done only using left join now
* removed separate _ids query as it was 90 % same as full one, extracting ids from full query now
=> VULN-1380,VULN-1069: feat(manager): display live counts in /vulnerabilities/cves API

database/schema/init_schema.sh
DB passwords are not set when deploying DB with empty volume because CYNDI_MOCK is unbound
1. init_schema fails with unbound error
2. openshift recreates the pod - logs from previous step are lost
3. init_shcema is now skipped and DB pod is running without any error in a log
4. no pod can connect to DB because passwords have not been set
=> fix(db): unbound variable in schema init

advisor_listener/advisor_listener.py
This caused that the messages did not get skip and systems with null insights_id got added.
=> fix(advisor_listener): skip invalid msgs instantly

common/config.py
- get `sslMode` and `rdsCa` form clowder conf
- try to fix `ConnectionError: PostgreSQL server at "vulnerability-engine-database:5432" rejected SSL upgrade`
- According to https://github.com/MagicStack/asyncpg/blob/master/asyncpg/connect_utils.py#L517-L530, it looks like `ssl_is_advisory` is set only when `sslmode=prefer`, but in our case ssl context is provided and it (probably) didn't set `ssl_is_advisory`... hard to tell
=> fix: db ssl with clowder

deploy/clowdapp.yaml
-  Bonfire can't deploy app if `namespace: ${ENV_NAME}` is set for secret
- define manager-admin url as public, so we can get it in tests (afaik it doesn't mean that it will have exposed route)
- remove unnecessary PATCH_HOST env var
=> fix: small clowdapp issues

manager/base.py, manager/cve_handler.py, manager/dashboard_handler.py, manager/report_handler.py, manager/status_handler.py, manager/system_handler.py, manager/vulnerabilities_handler.py
Fixes - VULN-{1736, 1726, 1725, 1721}
`cyndi_join` -  normal join, used when we need info from InventoryHosts table.
```
vulnerability=# EXPLAIN ANALYZE select * from system_platform as sp join inventory.hosts as ih on sp.inventory_id = ih.id;
QUERY PLAN                                                            
----------------------------------------------------------------------------------------------------------------------------------
Hash Join  (cost=1413.81..6114.97 rows=6436 width=946) (actual time=8.693..33.896 rows=5596 loops=1)
Hash Cond: (hosts_v1_9.id = sp.inventory_id)
->  Seq Scan on hosts_v1_9  (cost=0.00..2536.36 rows=18136 width=336) (actual time=0.010..9.700 rows=18028 loops=1)
->  Hash  (cost=842.36..842.36 rows=6436 width=594) (actual time=8.563..8.564 rows=6503 …
```
=> feat(manager): fix missing inconsistencies with cyndi

deploy/clowdapp.yaml, entrypoint.sh
- manager-admin had wrong port - I forget to change it to publicPort in my previous PR
- insights-engine can't be deployed because ci-ext jenkins couldn't access gitlab, thus disable it for now. I asked in #forum-clouddot how we should handle this case
=> fix clowder deployment

common/config.py, deploy/clowdapp.yaml
- fix getting hostname:port for private endpoints
- advisor-listener does not need opened port
=> fix(clowder): taskomatic and vmaas_sync are private endpoints

database/schema/upgrade_scripts/078-system-platform-uuid.sql, database/upgrade/upgrade.py
For example `TRUNCATE ... CASCADE` command produces notices which are printed to stderr by psql, and such migrations are marked as failed.
=> fix(database): run migrations as single transactions and detect errors better

vmaas_sync/vmaas_sync.py
Tested this on local CI copy of vmaas and engine db. I compared evaluations for all systems. The sorted evaluation was like few MB lighter, but like 30 seconds faster.
Reevaluation of 9000 systems:
Non-sorted evaluation was like 3:40 - 4:00 minutes long
Sorted evaluation was something 2:35 - 3:10 minutes long 
=> VULN-1523 refactor(vmaas_sync): reevaluate systems by rh_account_id

tests/vmaas_sync_tests/test_vmaas_sync.py, vmaas_sync/vmaas_sync.py
Previously syncs were blocking readiness and liveness probes, which caused restart or event fails in openshift.
The session and async with changes are just removing deprecated warnings.
=> fix(vmaas_sync): make every sync threaded

deploy/clowdapp.yaml
We cannot access rbac url if it is not set as dependency. It results in
running app without querying RBAC.
VULN-1866
=> fix(clowder): add rbac as dependency

common/config.py, deploy/clowdapp.yaml
list of all missing env vars based on the following script
```bash
#!/bin/bash
VARS_CODE=$(git grep -oP "(getenv\([\"']|environ\[[\"']|environ\.get\([\"'])\K[\w\d]+" | cut -d ':' -f2 | sort -u)
for var in $VARS_CODE; do
grep -q $var deploy/clowdapp.yaml
[ "$?" -ne "0" ] && missing="$missing\n$var"
done
echo -e $missing
```
```
AWS_REGION
CACHE_MINIMAL_ACCOUNT_SYSTEMS
CW_AWS_ACCESS_KEY_ID
CW_AWS_SECRET_ACCESS_KEY
CW_LOG_GROUP
DB_MAX_POOL_SIZE
DB_MIN_POOL_SIZE
DEBUG
DEFAULT_PAGE_SIZE
EMAIL_FROM
EMAIL_MONTHLY_TO
EMAIL_PARTIAL_MONTH_TO
EXCLUDE_ACCOUNTS
HOME
HOSTNAME
HTTP_REFERER
HTTP_USER_AGENT
KAFKA_GROUP_ID
KAFKA_HOST
KAFKA_PORT
MINIMAL_SCHEMA
PATH_INFO
PAYLOAD_TRACKER_TOPIC
POSTGRESQL_DATABASE
POSTGRESQL_HOST
POSTGRESQL_PORT
POSTGRESQL_SSL_MODE
POSTGRESQL_SSL_ROOT_CERT_PATH …
```
=> fix(clowder): add missing env vars to clowdapp

deploy/clowdapp.yaml
VULN-1909
in case anyone is calling vulnerability-engine-manager from inside the cluster (remediation had issues when we made a change in stage)
=> chore(clowder): add legacy port for manager

deploy/clowdapp.yaml
boproxy token secret is present in app-interface ephemeral-base and we should not overwrite it with the empty value from clowdapp.yaml
maybe it would be needed to delete old secrets from all ephemeral namespaces once this is merged
=> chore: use boproxy token from ephemeral-base

pr_check.sh
prcheck is killed because it takes more than 1h which is the limit for namespace reservation, let's try to limit executed tests only to test 'core' functionality -> critical and high requirements priority and critical and high test importance
last pr-check took:
- 16 min deploy
- 1 min until iqe ran tests
- 9 min vmaas sync
- 96% of tests ran and then it was killed
=> chore(prcheck): run tests only for 'core' requirements

.github/workflows/tests.yml, Dockerfile.test, notificator/notificator_queue.py
Vulnerabilities detected by advisor only (and not evaluator) got stuck in the queue, because currently we check for both evaluations to be done. Lets only check for advisor evaluation, this causes that.
Vulnerability by evaluator -> needs to wait for advisor evaluation
Vulnerability by advisor -> does not need to wait for evaluator
=> fix(notificator): advisor evaluation should have first priority

advisor_listener/advisor_listener.py, evaluator/evaluator.py, notificator/notificator.py, notificator/notificator_queue.py
default prefetch is 50, resulting in multiple queries
=> perf: fetch all rows at once instead of using cursor

tests/vmaas_sync_tests/test_vmaas_sync.py, vmaas_sync/vmaas_sync.py
This is most likely the issue because the AioHTTP server runs in the same loop as the websocket .
https://stackoverflow.com/questions/55918048/asyncio-semaphore-runtimeerror-task-got-future-attached-to-a-different-loop
VULN-2393
=> fix(vmaas_sync): fix semaphore init

manager/dashboard_handler.py
This change uses the affected CVE ids to get the number of CVEs which have some rule, we can omit the `system_vulnerabilities` scan.
=> perf(dashboard): reuse affected cves from overall cves query

listener/upload_listener.py, tests/listener_tests/test_upload_listener.py
Gather repository paths using a common pattern of `/content/*` and pass it to VMaaS within request as `repository_paths`.
Repository paths are taken from repository `mirrorlist` URLs. `$releasever` and `$basearch` placehoders are being substituted from newly added system profile facts (having the same name; https://github.com/RedHatInsights/inventory-schemas/pull/99).
Note that only RHUI repository paths are being sent.
VULN-2442
=> feat(listener): provide known repo paths out of RHUI mirrorlist URLs

manager/cve_handler.py, manager/system_handler.py
VULN-2515
UI hides Advisories columne when patch_access is False or None, we need to set it to True when using CFG.disable_patch_request feature
=> fix: set patch_access=true with advisories feature flag

common/config.py, common/strtobool.py, manager/base.py
`distutils.strtobool` returns `int` and is deprecated since python3.10
=> chore: drop distutils.strtobool

evaluator/evaluator.py
when CVE became reported in `cves` from vmaas - set advisories and remediation_type_id=2 when reported in `manually_fixable_cves` - set advisories=None, remediation_type_id=1
VULN-2515
=> fix(evaluator): update remediation type and advisory

evaluator/evaluator.py, evaluator/logic.py
we should not evaluate packages without epoch, it happens when inventory sends an incorrect package_list and we then show incorrect CVEs because vmaas assumes that epoch=0 if it is not provided
now, vmaas returns 400 if epoch is not present for a package and epoch_required=true, evaluation of a system is then skipped by evaluator
RHINENG-390
=> fix: require package epoch

listener/inventory_processor.py
Utilize relelasever from a system profile if RHSM version isn't set. This should improve reporting from RHUI systems.
VULN-2716
=> fix(listener): use releasever in vmaas_req

Dockerfile
Cherry-picking the Dockerfile change from https://github.com/RedHatInsights/vulnerability-engine/pull/1458 into the security-compliance branch
=> SC: Mark each assets directory as git 'safe.directory'

Dockerfile
When running rootless in OpenShift, the container runs rootless and therefore starts up with a random uid. The user ownership change on the assets directories now causes this git error:
```
sh-4.4$ git rev-parse HEAD
fatal: detected dubious ownership in repository at '/engine/insights_content_vulnerability_git'
To add an exception for this directory, call:
git config --global --add safe.directory /engine/insights_content_vulnerability_git
```
This PR marks the directories as "git safe" at the system level using `git config --system` instead of `git config --global` (using `--global` when executed as `root` stores the git config in `/root/.gitconfig` and this config will not be read by the non-root container user)
=> Mark each static assets dir as a git "safe.directory"

database/schema/upgrade_scripts/125-delete_system_vuln_package.sql, database/schema/ve_db_postgresql.sql
=> fix: delete from system_vulnerable_package when deleting system

evaluator/logic.py
VULN-2775
The rule arrive at little inconvenient format, which I missed when rewriting this evaluation part.
```
"rule_hits":{
"CVE-2017-5753":{
"details":"{\"cves\": {\"CVE-2017-5753\": \"The current combination and configuration of the CPU and kernel is not vulnerable.\", \"CVE-2017-5715\": false, \"CVE-2017-5754\": \"The current combination and configuration of the CPU and kernel is not vulnerable.\"}, \"type\": \"rule\", \"error_key\": \"KERNEL_CVE_2017_5753_4_CPU_ERROR_3\"}",
"rule_id":"CVE_2017_5753_4_cpu_kernel|KERNEL_CVE_2017_5753_4_CPU_ERROR_3"
}}
```
Even if this is in the `rule_hits` object, the system is not vulnerable to this CVE, because inside the `["rule_hits"]["CVE-2017-5753"][˝details"]["cves"]["CVE-2017-5753"]` the value is string, which is mitigation reason. If the …
=> fix(evaluator): correctly use the rule results

common/feature_flags.py, database/schema/ve_db_dev_data.sql, develfeatureflags.json, manager/base.py, manager/cve_handler.py, manager/dashbar_handler.py, manager/dashboard_handler.py, manager/main.py, manager/report_handler.py, manager/vulnerabilities_handler.py, tests/manager_tests/conftest.py, tests/manager_tests/test_dashbar_handler.py, tests/manager_tests/test_dashboard_handler.py, tests/manager_tests/test_report_handler.py, tests/manager_tests/test_vulnerabilities_handler.py
Creates `vulnerability.edge_parity` feature flag.
If enabled, edge systems are counted in major API responses counting affected systems (or systems affected by a rule).
VULN-2776
VULN-2765
=> feat: count edge systems affected in

manager/dashbar_handler.py, manager/dashboard_handler.py, manager/report_handler.py, tests/manager_tests/test_dashbar_handler.py, tests/manager_tests/test_dashboard_handler.py, tests/manager_tests/test_report_handler.py
like it's filtered in /vulnerabilities/cves API
this is a workaround for discrepancies in CVE data causing incorrect counts between different endpoints some fixable CVE like CVE-2018-20217 has empty advisory list even if it shouldn't have
this should be fixed properly later (the exclusion based on empty advisories_list removed)
VULN-2791
=> fix(manager): apply non-empty advisories list filter consistently in all APIs

common/config.py, conf/listener.env, deploy/clowdapp.yaml, listener/listener.py, platform_mock/platform_mock.py
I downgraded the insights-core, because it wont work with the newest version, the `system_profile` method is not called with system metadata but none in which the listener kafka message ends up with empty fields.
=> feat(listener): skip non-rhel systems

manager/filters.py, manager/vulnerabilities_handler.py
VULN-2789
advisory_available=true,false or null:
display all CVEs
advisory_available=true:
display CVEs having at least 1 advisory + CVEs with advisories affecting current env (should be a subset but non necessarily due to rules)
advisory_available=false:
display CVEs having 0 advisory + CVEs marked as unfixed in current env
=> fix(manager): improve advisory_available without affecting filter

build_deploy.sh
This PR adds the logic to the `build_deploy.sh` file to allow image building and tagging based on whether the branch name is `security-compliance`. 
=> Adding Security-Compliance Branch Build and Tagging Support

manager/vulnerabilities_handler.py
=> fix(manager): fix the condition

manager/base.py
=> fix(manager): referer should only check redhat DNS domain

vmaas_sync/vmaas_sync.py
vmaas shows latest_repo_change for the current page, so we need to store the latest timestamp, otherwise we are re-evaluating systems with the same repos
=> fix: store biggest latest_repo_change not just timestamp from last page

manager/base.py
When there are 2 users with different inventory groups in the same account, they can be invalidating cache for each other which will cause that api is slow for both of them. Cache only access to all inventory hosts. When a user doesn't have any inventory groups, then the query will be used without cache.
Stats from DB:
count of accounts | inventory groups
31581		  | []     // access to all hosts
1		  | [[]]   // access to ungrouped hosts only
6		  | access to only 1 inventory group
1		  | access to 1 group and to ungrouped hosts
1		  | access to multiple groups and ungrouped hosts
RHINENG-12465
=> fix: workaround cve_cache issue with inventory groups

manager/base.py
RHINENG-12111: 500 HTTP error when requesting api with account without persmissions
=> fix(manager): repair error handling when forbidden

manager/base.py
in ITless env the`report by CVEs` (/vulnerability/reports) was broken as it has a different domain
=> fix: add domain to allow download cve report to work in ITless
